export const LESSONS_7_TO_11 = {
  // ================= BÀI 7 =================
  7: {
    "买": "Chiết tự: Lưới võng bên trên vỏ sò Bối 贝 (tiền tệ cổ) ➔ Tung tiền ra để thu gom đồ vật về nhà ➔ Mua sắm.",
    "卖": "Chiết tự: Chữ Mãi 买 có thêm chữ Thập 十 (thặng dư, nhiều hàng) trên đầu ➔ Có nhiều hàng hóa dư dả đem đi bán ➔ Bán hàng.",
    "超市": "Ghép từ: 超 (Vượt trội, siêu đẳng, khổng lồ) + 市 (Chợ búa, khu thương mại) ➔ Khu chợ hiện đại quy mô siêu lớn ➔ Siêu thị.",
    "商店": "Ghép từ: 商 (Thương nhân buôn bán) + 店 (Cửa hiệu có mái che 广) ➔ Cửa hàng buôn bán hàng hóa.",
    "东西": "Ghép từ: 东 (Hướng Đông) + 西 (Hướng Tây) ➔ Thời cổ đi chợ Đông chợ Tây gom đủ các thứ đồ đạc ➔ Đồ vật, đồ đạc, đồ dùng.",
    "多少": "Ghép từ: 多 (Nhiều: hai vầng trăng chồng lên nhau) + 少 (Ít: ba hạt cát nhỏ) ➔ Mẫu câu hỏi ước lượng số lượng hoặc giá cả ➔ Bao nhiêu.",
    "钱": "Chiết tự: Kim 钅 (kim loại vàng bạc) + hai cây giáo Qua 戋 ➔ Thứ kim loại quý giá mà người đời tranh đoạt bảo vệ ➔ Tiền bạc.",
    "块": "Chiết tự: Thổ 土 (mảnh đất) + Quyết 夬 ➔ Cục bạc nén thời xưa được bẻ thành từng khối ➔ Đồng (tệ - khẩu ngữ), cục, miếng.",
    "元": "Chiết tự: Hai nét ngang 一 一 chỉ trời đất + Nhân 儿 con người ➔ Đơn vị tiền tệ gốc rễ hàng đầu ➔ Đồng (tệ - văn viết chính thức).",
    "毛": "Chiết tự: Sợi lông tơ mảnh mai ➔ Đơn vị tiền tệ nhỏ bằng 1/10 đồng tệ ➔ Hào (tiền Trung Quốc).",
    "分": "Chiết tự: Bát 八 + Đao 刀 (chia nhỏ tột cùng) ➔ Đơn vị tiền tệ nhỏ nhất bằng 1/100 đồng tệ ➔ Xu, phân.",
    "斤": "Chiết tự: Chiếc rìu nhỏ dùng làm quả cân tiêu chuẩn chợ xưa ➔ Cân Trung Quốc (= 500g = 0.5 kg).",
    "公斤": "Ghép từ: 公 (Công cộng, quốc tế chuẩn hóa) + 斤 (Cân) ➔ Đơn vị cân nặng chuẩn quốc tế ➔ Ki-lô-gam (1 kg = 2 cân TQ).",
    "贵": "Chiết tự: Trung 中 + Nhất 一 + Bối 贝 (vỏ sò tiền tệ) ➔ Món đồ đặt ở vị trí trung tâm quý giá tốn nhiều tiền bạc ➔ Đắt đỏ, quý phái.",
    "便宜": "Chiết tự: 便 (Tiện: thuận tiện) + 宜 (Nghi: thích hợp, vừa túi tiền) ➔ Món hàng giá cả rất vừa vặn, thuận lợi để mua ➔ Rẻ, giá rẻ.",
    "杯子": "Chiết tự: 杯 (Mộc 木 cái ly gỗ + Bất 不) + 子 (Hậu tố đồ vật) ➔ Chiếc cốc uống trà uống nước ➔ Cái cốc, cái ly.",
    "瓶子": "Chiết tự: 瓶 (Bình: Tịnh 并 hai bên + Ngoã 瓦 bình gốm nung) + 子 (Đồ vật) ➔ Chiếc bình, lọ gốm chứa chất lỏng ➔ Cái chai, cái lọ.",
    "碗": "Chiết tự: Thạch 石 (chế tác từ đá sứ) + Uyển 宛 (uốn cong lòng sâu) ➔ Chiếc bát gốm sứ lòng trũng đựng cơm canh ➔ Cái bát, chén.",
    "包": "Chiết tự: Hình một thai nhi nằm trọn trong bọc túi bảo bọc ➔ Cái túi xách, bọc lại, bao bọc.",
    "这": "Chiết tự: Văn 文 (hoa văn rõ ràng) + Xước 辶 (bước chân đi tới) ➔ Vật ngay sát chân nhìn rõ hoa văn ➔ Đây, này (khoảng cách gần).",
    "那": "Chiết tự: Nhĩ 阝 (vùng đất bên kia gò) ➔ Chỉ đối tượng ở phía xa tầm tay ➔ Kia, đó (khoảng cách xa).",
    "些": "Chiết tự: Thử 此 (chỗ này) + Nhị 二 (nhiều hơn một) ➔ Một vài vật gom lại ở đây ➔ Những, vài, một số.",
    "一点儿": "Ghép từ: 一点 (Một chấm nhỏ) + 儿 (Hậu tố uốn lưỡi) ➔ Một lượng vô cùng nhỏ bé ➔ Một chút, một ít.",
    "太": "Chiết tự: Chữ Đại 大 (to lớn) có thêm một giọt nước giọt mực tràn ra ngoài ➔ Đã vượt quá giới hạn chuẩn ➔ Quá, lắm.",
    "给": "Chiết tự: Mịch 纟 (sợi tơ bền chặt kết nối) + Hợp 合 (trao gửi vừa khít) ➔ Trao tận tay người khác món đồ ➔ Cho, đưa cho."
  },

  // ================= BÀI 8 =================
  8: {
    "现金": "Ghép từ: 现 (Xuất hiện ngay trước mắt) + 金 (Kim tiền vàng bạc) ➔ Tiền giấy kim loại cầm nắm được ngay ➔ Tiền mặt.",
    "刷卡": "Ghép từ: 刷 (Quẹt bàn chải kéo rẹt) + 卡 (Thẻ có chip trên dưới) ➔ Quẹt chiếc thẻ qua khe máy POS thanh toán ➔ Quẹt thẻ.",
    "卡": "Chiết tự: Thượng 上 (trên) và Hạ 下 (dưới) kẹp lại ở giữa ➔ Vật mỏng dẹp kẹp vừa vặn vào khe ➔ Thẻ ngân hàng, thẻ từ.",
    "微信": "Ghép từ: 微 (Vi: cực kỳ nhỏ gọn, tinh tế) + 信 (Tín: tin nhắn, trao gửi niềm tin) ➔ Ứng dụng gửi tin nhắn tiện lợi ➔ WeChat.",
    "扫码": "Ghép từ: 扫 (Quét sạch) + 码 (Mã số, mã vạch QR) ➔ Đưa camera quét qua hình mã vuông để trả tiền ➔ Quét mã QR.",
    "支付": "Ghép từ: 支 (Chi trả) + 付 (Phó: giao nộp tiền của) ➔ Hoàn tất việc trả tiền cho hóa đơn ➔ Thanh toán.",
    "付款": "Ghép từ: 付 (Trao cho) + 款 (Khoản tiền) ➔ Giao nộp khoản tiền phải thanh toán ➔ Trả tiền, thanh toán.",
    "买单": "Ghép từ: 买 (Mua hàng) + 单 (Tờ hóa đơn tính tiền) ➔ Kêu nhân viên đưa hóa đơn để trả tiền ➔ Thanh toán hóa đơn, tính tiền.",
    "银行": "Ghép từ: 银 (Bạc trắng) + 行 (Nơi giao thương buôn bán lớn) ➔ Nơi cất giữ và lưu chuyển tiền tệ ngân lượng ➔ Ngân hàng.",
    "用": "Chiết tự: Hình chiếc xô múc nước bằng gỗ dùng để làm việc ➔ Đem ra sử dụng phục vụ nhu cầu ➔ Dùng, sử dụng.",
    "可以": "Ghép từ: 可 (Khả năng cho phép) + 以 (Căn cứ vào) ➔ Đạt đủ điều kiện được chấp thuận ➔ Có thể, được phép.",
    "方便": "Ghép từ: 方 (Bốn phương thông suốt) + 便 (Tiện lợi, dễ dàng) ➔ Mọi nẻo đều thông thoáng không gặp trở ngại ➔ Tiện lợi, thuận tiện.",
    "找": "Chiết tự: Thủ 扌 (bàn tay) + Qua 戈 (cầm đuốc rà soát) ➔ Thò tay tìm kiếm đồ vật, đếm tiền thối lại ➔ Tìm kiếm; thối lại tiền thừa.",
    "零钱": "Ghép từ: 零 (Số lẻ, nhỏ giọt) + 钱 (Tiền) ➔ Những đồng tiền mệnh giá nhỏ lẻ ➔ Tiền lẻ.",
    "一共": "Ghép từ: 一 (Gom về một mối) + 共 (Chung sức, hợp lại) ➔ Hợp tất cả các khoản chi tiêu lại ➔ Tổng cộng.",
    "还是": "Ghép từ: 还 (Còn) + 是 (Là) ➔ Đặt ra hai ngả đường để chọn lựa trong câu hỏi ➔ Hay là (dùng trong câu hỏi chọn lựa).",
    "或者": "Ghép từ: 或 (Có lẽ) + 者 (Điều đó) ➔ Nêu phương án tương đương trong câu trần thuật ➔ Hoặc là (dùng trong câu khẳng định).",
    "多": "Chiết tự: Hai vầng trăng Tịch 夕 夕 chồng lên nhau ➔ Nhiều đêm tích lũy dồi dào của cải ➔ Nhiều.",
    "少": "Chiết tự: Tiểu 小 (nhỏ) bớt đi một nét phẩy ➔ Đã nhỏ lại còn bị vơi bớt ➔ Ít, thiếu.",
    "千": "Chiết tự: Thập 十 (mười) có thêm nét phẩy trên đỉnh ➔ Mười lần một trăm thành một ngàn ➔ Nghìn (1.000).",
    "万": "Chiết tự: Một nét ngang trên đầu nét uốn lượn tượng trưng cho số vạn dồi dào ➔ Mười nghìn (10.000, 1 vạn).",
    "免费": "Ghép từ: 免 (Miễn trừ, tha cho) + 费 (Chi phí, tiền bạc) ➔ Được xóa bỏ hoàn toàn chi phí, không tốn đồng nào ➔ Miễn phí.",
    "票": "Chiết tự: Phiêu 覀 (bay bổng) + Thị 示 (dấu ấn thần linh đóng mộc) ➔ Mảnh giấy có đóng dấu xác nhận quyền lên tàu xe ➔ Tấm vé."
  },

  // ================= BÀI 9 =================
  9: {
    "衣服": "Chiết tự: 衣 (Hình chiếc áo cổ dài hai tay áo) + 服 (Chấp nhận khoác lên thân thể) ➔ Trang phục mặc hàng ngày ➔ Quần áo.",
    "穿": "Chiết tự: Huyệt 穴 (hang hốc, ống quần) + Nha 牙 (xỏ răng vào) ➔ Xỏ chân tay xuyên qua ống quần ống áo ➔ Mặc áo, xỏ giày.",
    "件": "Chiết tự: Nhân 亻 (người) + Ngưu 牛 (con trâu to) ➔ Tách riêng từng con trâu to lớn ➔ Chiếc, bộ (lượng từ đếm quần áo, sự việc).",
    "颜色": "Ghép từ: 颜 (Khuôn mặt rạng rỡ) + 色 (Sắc thái, ánh sắc) ➔ Sắc thái ánh sáng phản chiếu bắt mắt ➔ Màu sắc.",
    "红色": "Chiết tự: 红 (Mịch 纟 sợi tơ lụa + Công 工 nhuộm sắc tươi thắm) + 色 (Màu) ➔ Màu sắc rực rỡ may mắn của lụa đào ➔ Màu đỏ.",
    "白色": "Chiết tự: 白 (Hạt gạo trắng ngần bóc vỏ) + 色 (Màu) ➔ Màu tinh khôi không tì vết ➔ Màu trắng.",
    "黑色": "Chiết tự: 黑 (Ống khói bếp bốc lên bồ hóng dính than đen) + 色 (Màu) ➔ Màu tối đen như mực ➔ Màu đen.",
    "黄色": "Chiết tự: 黄 (Mảnh đất phù sa màu mỡ mùa thu hoạch) + 色 (Màu) ➔ Màu rực rỡ hoàng gia, đất mẹ ➔ Màu vàng.",
    "蓝色": "Chiết tự: 蓝 (Thảo 艹 cây chàm ngâm chậu Giám 监 tạo màu xanh biếc) + 色 ➔ Màu sắc của bầu trời bao la ➔ Màu xanh da trời, xanh lam.",
    "绿色": "Chiết tự: 绿 (Mịch 纟 tơ nhuộm màu chồi non Lục 录) + 色 ➔ Sắc màu tươi tốt của cây cỏ mùa xuân ➔ Màu xanh lá cây.",
    "裤子": "Chiết tự: 裤 (Y 衤 vải vóc + Khố 库 kho chứa hai chân) + 子 ➔ Trang phục hai ống che kín từ eo xuống chân ➔ Cái quần.",
    "裙子": "Chiết tự: 裙 (Y 衤 vải quần áo + Quân 君 tà áo thướt tha quý tộc) + 子 ➔ Trang phục xòe rộng duyên dáng của phái nữ ➔ Cái váy.",
    "鞋子": "Chiết tự: 鞋 (Cách 革 da thú dai bền + Khuê 圭 đất nung) + 子 ➔ Đồ da bọc quanh bàn chân để đạp lên đất cát ➔ Đôi giày.",
    "帽子": "Chiết tự: 帽 (Cân 巾 tấm vải che đỉnh đầu Mạo 冒) + 子 ➔ Đồ đội lên đầu để che nắng mưa làm đẹp ➔ Cái mũ, nón.",
    "大": "Chiết tự: Hình một người dang rộng cả hai tay và hai chân hết cỡ ➔ Tầm vóc to lớn bao la ➔ To, lớn.",
    "小": "Chiết tự: Một vật ở giữa bị tách hai giọt nhỏ hai bên ➔ Kích thước thu bé lại ➔ Nhỏ, bé.",
    "新": "Chiết tự: Lập 立 (dựng lên) + Mộc 木 (cây gỗ) + Cân 斤 (rìu đẽo) ➔ Vừa đốn cây gỗ mới toanh về làm nhà ➔ Mới mẻ, tinh khôi.",
    "旧": "Chiết tự: Một nét phẩy đặt trên chữ Nhật 日 (nhiều ngày tháng trôi qua phai mòn) ➔ Đồ vật đã qua thời gian dài ➔ Cũ kỹ, xưa cũ.",
    "长": "Chiết tự: Hình tượng mái tóc dài của vị trưởng lão tung bay trong gió ➔ Chiều kích trải dài thênh thang ➔ Dài.",
    "短": "Chiết tự: Thỉ 矢 (mũi tên ngắn) + Đậu 豆 (cái bát hạt đậu nhỏ bé) ➔ Mũi tên ngắn hơn ngọn giáo dài ➔ Ngắn gọn, thấp ngắn.",
    "漂亮": "Ghép từ: 漂 (Nước 氵 trong veo gợn sóng) + 亮 (Ánh sáng rực rỡ) ➔ Khuôn mặt rạng ngời như mặt hồ đón nắng ➔ Xinh đẹp, đẹp đẽ.",
    "试": "Chiết tự: Ngôn 讠 (lời nói) + Thức 式 (khuôn mẫu định sẵn) ➔ Thử ướm thử vào khuôn xem có vừa vặn không ➔ Thử nghiệm, thử đồ.",
    "条": "Chiết tự: Cành cây thon dài rủ xuống đất ➔ Lượng từ đếm những vật dài uốn lượn như con đường, chiếc quần, con cá.",
    "双": "Chiết tự: Hai bàn tay Hựu 又 又 sóng đôi bên nhau ➔ Hai vật đi liền thành một cặp tương xứng ➔ Đôi (giày, đũa).",
    "真": "Chiết tự: Đỉnh nấu đan dược của đạo sĩ đạt tới độ tinh khiết tuyệt đối ➔ Tính chân thật không chút giả tạo ➔ Thật, quả thật."
  },

  // ================= BÀI 10 =================
  10: {
    "房间": "Ghép từ: 房 (Hộ 户 cánh cửa + Phương 方 góc nhà) + 间 (Mặt trời 日 rọi qua khe cửa 门) ➔ Khoảng không gian riêng tư ngăn nắp ➔ Căn phòng.",
    "客厅": "Ghép từ: 客 (Khách khứa tới thăm) + 厅 (Sảnh rộng có mái che 厂) ➔ Gian phòng rộng rãi đón tiếp bạn bè ➔ Phòng khách.",
    "厨房": "Ghép từ: 厨 (Bếp núc nấu nướng bên lò lửa) + 房 (Gian phòng) ➔ Nơi chế biến các món ăn thơm ngon ➔ Nhà bếp.",
    "洗手间": "Ghép từ: 洗手 (Rửa đôi bàn tay sạch sẽ) + 间 (Gian phòng) ➔ Căn phòng dùng để vệ sinh cá nhân ➔ Nhà vệ sinh.",
    "门": "Chiết tự: Hình hai cánh cổng gỗ khép mở nơi lối ra vào của ngôi nhà cổ ➔ Cánh cửa, cổng lớn.",
    "窗户": "Ghép từ: 窗 (Khung cửa có lỗ đón gió trên mái 穴) + 户 (Cánh cửa nhỏ) ➔ Khung cửa mở ra đón ánh nắng và gió trời ➔ Cửa sổ.",
    "桌子": "Chiết tự: 桌 (Cao 早 trên bệ đỡ gỗ Mộc 木) + 子 (Đồ vật) ➔ Mặt phẳng gỗ bốn chân để làm việc và ăn uống ➔ Cái bàn.",
    "椅子": "Chiết tự: 椅 (Mộc 木 gỗ tốt + Kỳ 奇 ngồi lên kỳ thú) + 子 ➔ Đồ vật bằng gỗ có tựa lưng để ngồi ➔ Cái ghế.",
    "床": "Chiết tự: Mái nhà che Quảng 广 cho tấm phản gỗ Mộc 木 bằng phẳng ➔ Nơi ngả lưng êm ái mỗi đêm ➔ Cái giường.",
    "灯": "Chiết tự: Hỏa 火 (ngọn lửa bập bùng) + Đinh 丁 (cây cọc thắp sáng) ➔ Thiết bị phát ra ánh sáng xua tan bóng tối ➔ Đèn, bóng điện.",
    "上": "Chiết tự: Một vạch chuẩn nằm dưới, nét đứng và nét ngang vươn lên phía trên ➔ Hướng lên cao, phía trên.",
    "下": "Chiết tự: Một vạch chuẩn nằm trên, nét sổ và nét chấm chỉ xuống dưới ➔ Hướng xuống thấp, phía dưới.",
    "里": "Chiết tự: Điền 田 (thửa ruộng) + Thổ 土 (mảnh đất) ➔ Nằm sâu bên trong ranh giới bờ cõi làng quê ➔ Bên trong, trong lòng.",
    "外": "Chiết tự: Tịch 夕 (đêm tối) + Bốc 卜 (bói toán) ➔ Điềm bói vượt ra ngoài dự đoán bình thường ➔ Bên ngoài, ngoài.",
    "开": "Chiết tự: Hai bàn tay đẩy hai then cài cửa gỗ bung rộng ra ➔ Bắt đầu hoạt động, đẩy cửa ➔ Mở cửa, bật điện, lái xe.",
    "关": "Chiết tự: Hai then cài then sắt khép chặt cánh cửa phòng ngự ➔ Ngăn cách không cho lưu thông ➔ Đóng lại, tắt điện.",
    "住": "Chiết tự: Nhân 亻 (con người) + Chủ 主 (ngọn đèn chủ ngự trị) ➔ Con người an cư lạc nghiệp thắp sáng ngọn đèn nhà mình ➔ Sinh sống, ở, cư ngụ.",
    "楼": "Chiết tự: Mộc 木 (cột gỗ vững chãi) + Lâu 娄 (tầng tầng lớp lớp) ➔ Công trình xây dựng nhiều tầng vươn cao ➔ Tòa nhà, tầng gác.",
    "大楼": "Ghép từ: 大 (To lớn quy mô) + 楼 (Tòa nhà nhiều tầng) ➔ Công trình kiến trúc bề thế nhiều tầng ➔ Tòa nhà lớn, cao ốc.",
    "地方": "Ghép từ: 地 (Thổ 土 đất đai) + 方 (Bốn phương tám hướng) ➔ Một khoảng không gian xác định trên mặt đất ➔ Nơi chốn, địa điểm.",
    "干净": "Ghép từ: 干 (Khô ráo sạch bóng) + 净 (Nước 氵 rửa sạch không vướng bụi bặm) ➔ Tinh tươm, không một hạt bụi bẩn ➔ Sạch sẽ.",
    "脏": "Chiết tự: Nguyệt 月 (thân thể da thịt) + Trang 庄 (bùn đất dính đầy) ➔ Bám đầy chất bẩn lem luốc ➔ Bẩn thỉu, dơ dáy.",
    "把": "Chiết tự: Thủ 扌 (bàn tay nắm) + Ba 巴 (ôm ghì lấy) ➔ Nắm giữ phần cán cầm ➔ Chiếc (lượng từ ghế có tay vịn, con dao, cây dù).",
    "张": "Chiết tự: Cung 弓 (cây cung) + Trường 长 (kéo dài) ➔ Kéo căng một bề mặt phẳng rộng ➔ Tờ, tấm (lượng từ bàn, giường, tờ giấy).",
    "放": "Chiết tự: Phương 方 (vị trí vuông vắn) + Phộc 攵 (bàn tay hạ xuống) ➔ Đặt vật xuống vị trí cố định an toàn ➔ Đặt, để, buông."
  },

  // ================= BÀI 11 =================
  11: {
    "手机": "Ghép từ: 手 (Bàn tay cầm nắm) + 机 (Cỗ máy vi mạch thông minh) ➔ Thiết bị liên lạc thông minh gọn nhẹ cầm tay ➔ Điện thoại di động.",
    "电脑": "Ghép từ: 电 (Tia chớp điện năng) + 脑 (Bộ não tư duy của con người) ➔ Bộ não nhân tạo vận hành bằng điện ➔ Máy vi tính.",
    "电话": "Ghép từ: 电 (Dòng điện) + 话 (Lời nói, đàm thoại) ➔ Thiết bị truyền tải giọng nói qua đường dây điện ➔ Điện thoại, cuộc gọi.",
    "打电话": "Ghép từ: 打 (Thủ 扌 bấm gõ phím số) + 电话 (Điện thoại) ➔ Quay số gọi trò chuyện với người phương xa ➔ Gọi điện thoại.",
    "网": "Chiết tự: Hình chiếc lưới đan chéo các sợi dây liên kết chằng chịt ➔ Mạng lưới liên kết dữ liệu toàn cầu ➔ Mạng internet, lưới.",
    "上网": "Ghép từ: 上 (Bước lên trên) + 网 (Không gian mạng) ➔ Kết nối thiết bị vào xa lộ thông tin thế giới ➔ Lên mạng, lướt web.",
    "拍照": "Ghép từ: 拍 (Thủ 扌 vỗ, ấn nút chớp máy) + 照 (Nhật 日 ánh sáng rọi qua ống kính) ➔ Bấm nút thu lại khoảnh khắc ánh sáng ➔ Chụp ảnh.",
    "照片": "Ghép từ: 照 (Ánh sáng chiếu rọi) + 片 (Mảnh film mỏng dẹt) ➔ Tấm ảnh in ghi dấu kỷ niệm ➔ Bức ảnh, tấm hình.",
    "发": "Chiết tự: Mũi tên bắn vút khỏi cánh cung bay về phía trước ➔ Đưa thông tin hoặc tín hiệu đi xa ➔ Gửi đi, phát hành.",
    "信息": "Ghép từ: 信 (Tin cậy) + 息 (Hơi thở, thông điệp) ➔ Những thông điệp số được trao gửi qua lại ➔ Tin nhắn, thông tin.",
    "电影": "Ghép từ: 电 (Ánh sáng điện tử) + 影 (Bóng hình chuyển động trên màn chiếu) ➔ Tác phẩm nghệ thuật hình ảnh chuyển động ➔ Bộ phim, điện ảnh.",
    "电视": "Ghép từ: 电 (Tín hiệu điện) + 视 (Thị: đôi mắt chăm chú theo dõi) ➔ Màn hình thu phát hình ảnh truyền hình ➔ Ti vi, truyền hình.",
    "音乐": "Ghép từ: 音 (Âm thanh thánh thót) + 乐 (Nhạc điệu rộn ràng vui tươi) ➔ Giai điệu trầm bổng nuôi dưỡng tâm hồn ➔ Âm nhạc.",
    "喂": "Chiết tự: Khẩu 口 (mở miệng cất tiếng) + Úy 畏 ➔ Tiếng reo chào báo hiệu mình đang lắng nghe đầu dây bên kia ➔ A-lô (khi nghe điện thoại).",
    "号码": "Ghép từ: 号 (Số hiệu định danh) + 码 (Ký tự mã vạch bằng đá thạch 石) ➔ Dãy số nhận diện tài khoản hoặc liên lạc ➔ Mã số, số điện thoại.",
    "问": "Chiết tự: Khẩu 口 (cái miệng hé mở) ngay giữa khung cửa Môn 门 ➔ Ghé đầu vào cổng cất tiếng hỏi thăm chủ nhà ➔ Hỏi thăm, hỏi han.",
    "答": "Chiết tự: Trúc 竹 (thẻ tre ghi hồi đáp) + Hợp 合 (khớp đúng nội dung) ➔ Viết lời giải đáp thỏa đáng cho câu hỏi ➔ Trả lời, hồi đáp.",
    "玩": "Chiết tự: Vương 王 (viên ngọc quý) + Nguyên 元 (đứa trẻ bắt đầu) ➔ Cầm viên ngọc quý chơi đùa vui thích ➔ Vui chơi, chơi đùa.",
    "忙": "Chiết tự: Tâm 忄 (con tim) + Vong 亡 (mất hút, bấn loạn) ➔ Công việc dồn dập khiến tâm trí quay cuồng ➔ Bận rộn, tất bật.",
    "等": "Chiết tự: Trúc 竹 (ghi việc lên thẻ tre) + Tự 寺 (ngôi chùa thanh tịnh) ➔ Ngồi yên thanh tịnh kiên nhẫn đợi đúng thời khắc ➔ Chờ đợi, đợi.",
    "快": "Chiết tự: Tâm 忄 (trái tim háo hức) + Quyết 夬 (nhanh chóng dứt khoát) ➔ Tốc độ lướt đi vùn vụt trong chớp mắt ➔ Nhanh chóng, mau lẹ.",
    "慢": "Chiết tự: Tâm 忄 (tâm trạng thong dong) + Mạn 曼 (kéo dài lê thê) ➔ Từng bước khoan thai không vội vã ➔ Chậm rãi, từ tốn.",
    "好玩": "Ghép từ: 好 (Tuyệt vời) + 玩 (Chơi đùa) ➔ Trò chơi hoặc hoạt động mang lại niềm vui sảng khoái ➔ Thú vị, vui nhộn."
  }
};
