export const LESSONS_17_TO_20 = {
  // ================= BÀI 17 =================
  17: {
    "身体": "Ghép từ: 身 (Thân hình người mang thai nở nang) + 体 (Nhân 亻 + Bản 本: gốc rễ của con người) ➔ Thân thể, vóc dáng và sức khỏe ➔ Cơ thể, sức khỏe.",
    "生病": "Ghép từ: 生 (Nảy sinh) + 病 (Bộ Nạch 疒 giường bệnh + Bính 丙) ➔ Cơ thể nhiễm mầm bệnh đau ốm ➔ Bị ốm, ngã bệnh.",
    "感冒": "Chiết tự: Cảm 感 (Tâm tim cảm nhận gió lạnh) + Mạo 冒 (mạo hiểm đón gió độc) ➔ Cơ thể nhiễm phong hàn hắt hơi sổ mũi ➔ Cảm cúm.",
    "发烧": "Ghép từ: 发 (Bộc phát ra ngoài) + 烧 (Hỏa 火 ngọn lửa thiêu đốt) ➔ Nhiệt độ cơ thể tăng vọt hầm hập như lửa đốt ➔ Sốt, phát sốt.",
    "疼": "Chiết tự: Nạch 疒 (nằm bẹp trên giường) + Đông 冬 (băng giá buốt nhức) ➔ Cảm giác buốt nhức buốt đau ➔ Đau đớn, nhức nhối.",
    "药": "Chiết tự: Thảo 艹 (cây cỏ thảo mộc) + Lạc 乐 (nhạc điệu chữa lành tâm hồn) ➔ Thảo dược quý giúp cơ thể khỏi bệnh ➔ Thuốc chữa bệnh.",
    "吃药": "Ghép từ: 吃 (Đưa vào miệng nuốt) + 药 (Viên thuốc) ➔ Uống thuốc điều trị bệnh theo chỉ dẫn bác sĩ ➔ Uống thuốc (dùng từ 'ăn').",
    "看病": "Ghép từ: 看 (Bác sĩ thăm khám, quan sát) + 病 (Căn bệnh) ➔ Đến gặp bác sĩ để chẩn đoán điều trị ➔ Đi khám bệnh.",
    "头": "Chiết tự: Bộ Đậu 豆 (cái bát bệ đỡ) có hai chấm trên trán ➔ Phần cao nhất trên cơ thể con người ➔ Cái đầu.",
    "眼睛": "Ghép từ: 眼 (Mục 目 con mắt) + 睛 (Mục 目 + Thanh 青 tròng mắt trong xanh long lanh) ➔ Cửa sổ tâm hồn để nhìn ngắm vạn vật ➔ Đôi mắt.",
    "鼻子": "Chiết tự: 鼻 (Tự 自 chiếc mũi thở + Tỳ 畀) + 子 ➔ Cơ quan thính giác và hô hấp ở giữa mặt ➔ Cái mũi.",
    "嘴": "Chiết tự: Khẩu 口 (miệng) + Chùy 觜 (mỏ chim cứng) ➔ Khẩu hình dùng để ăn uống và trò chuyện ➔ Cái miệng, bờ môi.",
    "耳朵": "Chiết tự: 耳 (Hình vẽ vành tai uốn lượn đón âm thanh) + 朵 (Bông hoa nhỏ) ➔ Đôi tai tiếp nhận âm thanh ➔ Cái tai.",
    "手": "Chiết tự: Hình bàn tay xòe rộng 5 ngón khéo léo lao động sáng tạo ➔ Bàn tay.",
    "脚": "Chiết tự: Nguyệt 月 (thịt cơ bắp) + Khước 却 ➔ Bộ phận tiếp đất nâng đỡ toàn thân bước đi ➔ Bàn chân.",
    "腿": "Chiết tự: Nguyệt 月 (da thịt) + Thoái 退 (bước lui tiến linh hoạt) ➔ Cẳng chân dài giúp ta chạy nhảy ➔ Cái chân, cẳng chân.",
    "肚子": "Chiết tự: 肚 (Nguyệt 月 da thịt + Thổ 土 khoang đất chứa thức ăn) + 子 ➔ Khoang bụng tiêu hóa thức ăn ➔ Cái bụng.",
    "好": "Chiết tự: Nữ 女 (người mẹ) + Tử 子 (đứa con) ➔ Người mẹ chăm sóc con chu đáo bệnh tình tiêu tan ➔ Khỏi bệnh, lành lặn; tốt đẹp.",
    "舒服": "Ghép từ: 舒 (Xá 舍 buông bỏ thư thái + Dư 予) + 服 (Hòa hợp với thân thể) ➔ Thân tâm khoan khoái không chút mệt mỏi ➔ Dễ chịu, thoải mái.",
    "难受": "Ghép từ: 难 (Gian nan, khó khăn) + 受 (Thụ: đón nhận, chịu đựng) ➔ Cơ thể bức bối đau nhức khó lòng chịu nổi ➔ Khó chịu trong người.",
    "检查": "Ghép từ: 检 (Mộc cọc gông kiểm chứng) + 查 (Mộc tra cứu kỹ càng từng kẽ) ➔ Rà soát xét nghiệm để tìm ra nguyên nhân ➔ Kiểm tra, xét nghiệm.",
    "健康": "Ghép từ: 健 (Nhân người tráng kiện vững vàng) + 康 (Mái nhà no đủ thóc lúa) ➔ Thể chất sung mãn và tinh thần an lành ➔ Khỏe mạnh, sức khỏe.",
    "得": "Chiết tự: Xích 彳 (bước chân) + Đán 旦 (mặt trời lên) + Thốn 寸 (tấc lòng) ➔ Mệnh lệnh bắt buộc phải thực thi ngay ➔ Phải (bắt buộc làm gì)."
  },

  // ================= BÀI 18 =================
  18: {
    "运动": "Chiết tự: 运 (Xước 辶 di chuyển luân phiên) + 动 (Vân mây trôi + Lực 力 sức mạnh cơ bắp) ➔ Rèn luyện thể lực cho cơ thể săn chắc ➔ Thể thao, vận động.",
    "喜欢": "Ghép từ: 喜 (Trống đánh miệng cười hoan hỷ) + 欢 (Mở miệng reo mừng) ➔ Niềm say mê yêu mến từ tận đáy lòng ➔ Thích, yêu thích.",
    "爱好": "Ghép từ: 爱 (Trái tim yêu thương đong đầy) + 好 (Thích thú điều tốt lành) ➔ Thú vui tao nhã theo đuổi lúc rảnh rỗi ➔ Sở thích.",
    "踢足球": "Ghép từ: 踢 (Túc 足 tung chân sút mạnh) + 足球 (Quả bóng tròn) ➔ Môn thể thao vua dùng chân tranh bóng trên sân cỏ ➔ Đá bóng.",
    "足球": "Ghép từ: 足 (Đôi chân) + 球 (Vương viên ngọc tròn lăn lông lốc) ➔ Quả bóng tròn thi đấu trên sân cỏ ➔ Quả bóng đá.",
    "跑步": "Ghép từ: 跑 (Túc 足 tung chân chạy) + 步 (Hai dấu chân sải bước liên hồi) ➔ Môn thể thao chạy bộ rèn luyện sức bền ➔ Chạy bộ.",
    "游泳": "Ghép từ: 游 (Nước 氵 lướt sóng phương xa) + 泳 (Nước 氵 vùng vẫy bơi lội) ➔ Hoạt động vùng vẫy bơi lội dưới làn nước mát ➔ Bơi lội.",
    "唱歌": "Ghép từ: 唱 (Khẩu 口 cất tiếng ngâm nga theo xướng ngôn) + 歌 (Khả Khả miệng ngân vang giai điệu) ➔ Cất cao giọng hát bài ca yêu thích ➔ Hát bài hát.",
    "跳舞": "Ghép từ: 跳 (Túc 足 nhún nhảy trên không) + 舞 (Người cầm cành hoa múa lượn duyên dáng) ➔ Vũ điệu hình thể uyển chuyển theo tiếng nhạc ➔ Nhảy múa, khiêu vũ.",
    "旅游": "Ghép từ: 旅 (Cờ đoàn lữ hành phấp phới) + 游 (Chu du ngắm cảnh non nước) ➔ Chuyến đi xa khám phá danh lam thắng cảnh ➔ Đi du lịch.",
    "游戏": "Ghép từ: 游 (Vui chơi lướt khắp nơi) + 戏 (Cầm kích giáo đùa giỡn trong màn kịch) ➔ Trò chơi giải trí điện tử hoặc dân gian ➔ Trò chơi, Game.",
    "一起": "Ghép từ: 一 (Cùng một khối) + 起 (Chạy dậy hành động) ➔ Đồng hành sát cánh bên nhau không rời ➔ Cùng nhau.",
    "比赛": "Ghép từ: 比 (Hai người đứng so tài cao thấp) + 赛 (Treo giải thưởng Bối 贝 tranh tài) ➔ Cuộc so tài phân định người thắng kẻ thua ➔ Trận đấu, thi đấu.",
    "赢": "Chiết tự: Vong 亡 (nguy cơ) + Khẩu 口 (kêu gọi) + Nguyệt 月 (nỗ lực từng ngày) + Bối 贝 (tiền bạc) + Phàm 凡 (chu đáo) ➔ Hội tụ đủ 5 yếu tố đỉnh cao để chạm đỉnh vinh quang ➔ Chiến thắng.",
    "输": "Chiết tự: Xa 车 (xe cộ) + Du 俞 (rỗng tuếch đổ nghiêng) ➔ Xe hàng bị lật đổ mất sạch không còn gì ➔ Thua cuộc, thất bại.",
    "经常": "Ghép từ: 经 (Đường thẳng xuyên suốt) + 常 (Thường xuyên diễn ra) ➔ Thói quen lặp đi lặp lại rất nhiều lần ➔ Thường xuyên.",
    "公园": "Ghép từ: 公 (Công cộng cho mọi người) + 园 (Khu vườn 囗 trồng cây hoa quý) ➔ Khu vườn xanh mát cho người dân dạo mát ➔ Công viên.",
    "爬山": "Ghép từ: 爬 (Móng vuốt bám chặt vách đá trèo lên) + 山 (Ngọn núi cao vút) ➔ Hoạt động leo lên đỉnh núi rèn luyện ý chí ➔ Leo núi.",
    "画": "Chiết tự: Tay cầm bút lông vạch ranh giới quanh 4 bờ ruộng Điền 田 ➔ Tác phẩm hội họa đường nét sắc sảo ➔ Vẽ; bức tranh.",
    "画画": "Ghép từ: 画 (Động tác cầm cọ vẽ) + 画 (Tác phẩm bức tranh nghệ thuật) ➔ Cầm cọ tô điểm màu sắc lên trang giấy ➔ Vẽ tranh.",
    "跟": "Chiết tự: Túc 足 (bàn chân) + Cấn 艮 (dừng gót ngoái nhìn) ➔ Bước từng bước sát gót theo chân người phía trước ➔ Cùng, đi theo với.",
    "打球": "Ghép từ: 打 (Thủ 扌 dùng tay đập vỗ vợt) + 球 (Quả bóng tròn) ➔ Chơi các môn thể thao dùng tay điều khiển bóng ➔ Đánh bóng (bóng rổ, bóng chuyền, cầu lông).",
    "特别": "Ghép từ: 特 (Ngưu con bò đực độc nhất vô nhị) + 别 (Tách biệt khỏi đám đông) ➔ Khác biệt hoàn toàn, vượt trội ấn tượng ➔ Đặc biệt, cực kỳ."
  },

  // ================= BÀI 19 =================
  19: {
    "快乐": "Ghép từ: 快 (Khoan khoái trong lòng) + 乐 (Tiếng đàn reo vui hân hoan) ➔ Cảm giác hạnh phúc ngập tràn tiếng cười ➔ Vui sướng, hạnh phúc.",
    "难过": "Ghép từ: 难 (Gian nan trắc trở) + 过 (Băng qua) ➔ Cảm giác nghẹn ngào khó lòng nuốt trôi trong lòng ➔ Buồn bã, đau lòng.",
    "生气": "Ghép từ: 生 (Bùng nổ sinh sôi) + 气 (Luồng hỏa khí bốc lên đầu) ➔ Cơn giận đùng đùng bốc hỏa tức tối ➔ Tức giận, giận dỗi.",
    "害怕": "Ghép từ: 害 (Mối nguy hiểm rình rập) + 怕 (Tâm 忄 run rẩy trắng bệch 白) ➔ Tim đập thình thịch mặt mày tái mét vì kinh hoàng ➔ Sợ hãi.",
    "聪明": "Ghép từ: 聪 (Nhĩ 耳 tai thính lắng nghe + Tổng thấu triệt) + 明 (Nhật Nguyệt mắt sáng tinh tường) ➔ Tai nghe mắt thấy hiểu thấu mọi điều ➔ Thông minh, lanh lợi.",
    "努力": "Ghép từ: 努 (Nô lệ dốc lòng) + 力 (Sức mạnh cơ bắp) ➔ Dốc cạn tâm trí và sức lực để đạt được mục tiêu ➔ Cố gắng, chăm chỉ nỗ lực.",
    "热情": "Ghép từ: 热 (Hừng hực lửa nóng) + 情 (Tình cảm chân thành) ➔ Đón tiếp niềm nở bằng cả tấm lòng nhiệt huyết ➔ Nhiệt tình, hiếu khách.",
    "认真": "Ghép từ: 认 (Nhận diện kỹ càng) + 真 (Chân thật không chút lơ là) ➔ Làm việc cẩn thận tỉ mỉ từng li từng tí ➔ Nghiêm túc, chăm chút.",
    "帅": "Chiết tự: Tấm cờ soái lệnh bay phấp phới của vị tướng quân uy phong lẫm liệt ➔ Dáng vẻ khôi ngô hào hoa của đấng nam nhi ➔ Đẹp trai, phong độ.",
    "美": "Chiết tự: Dương 羊 (con cừu) + Đại 大 (to béo mập mạp) ➔ Biểu tượng của sự phồn vinh và cái đẹp chuẩn mực cổ đại ➔ Tươi đẹp, mỹ miều.",
    "觉得": "Ghép từ: 觉 (Giác quan cảm nhận) + 得 (Nắm bắt được) ➔ Nhận định và suy nghĩ xuất phát từ trực giác ➔ Cảm thấy, thấy rằng.",
    "希望": "Ghép từ: 希 (Mỏng manh sợi tơ thêu) + 望 (Vọng: trèo lên gò đất ngóng trông vầng trăng) ➔ Ngước nhìn về tương lai với niềm tin tốt đẹp ➔ Hy vọng, mong mỏi.",
    "比": "Chiết tự: Hai người đứng kề vai sát cánh đọ chiều cao ➔ Đặt hai đối tượng lên bàn cân so tài ➔ So với (trong câu so sánh hơn).",
    "更": "Chiết tự: Bàn tay Phộc gõ nhịp canh chuyển giao sang mức độ cao hơn ➔ Thêm một bậc vượt trội hơn nữa ➔ Càng, hơn nữa.",
    "笑": "Chiết tự: Trúc 竹 (rặng tre đu đưa theo gió) + Yêu 夭 (uốn lượn hớn hở) ➔ Khóe miệng nở nụ cười rạng rỡ sảng khoái ➔ Cười, mỉm cười.",
    "哭": "Chiết tự: Hai chữ Khẩu 口 口 mở to + Khuyển 犬 (con chó sủa rên rỉ) ➔ Miệng òa khóc giọt lệ tuôn trào đau xót ➔ Khóc lóc, lệ rơi.",
    "讨厌": "Ghép từ: 讨 (Ngôn 讠 khiêu khích hạch sách) + 厌 (Chán ngấy đến tận cổ) ➔ Cảm giác bài xích không muốn lại gần ➔ Ghét bỏ, đáng ghét.",
    "可爱": "Ghép từ: 可 (Đáng để) + 爱 (Yêu thương che chở) ➔ Nét ngây thơ xinh xắn khiến ai nhìn cũng muốn cưng chiều ➔ Đáng yêu, dễ thương.",
    "奇怪": "Ghép từ: 奇 (Cưỡi ngựa đặc dị lạ lùng) + 怪 (Tâm 忄 kinh ngạc ngỡ ngàng) ➔ Hiện tượng khác thường bất ngờ gây sửng sốt ➔ Kỳ lạ, quái lạ."
  },

  // ================= BÀI 20 =================
  20: {
    "复习": "Ghép từ: 复 (Lặp lại lần nữa) + 习 (Tập luyện đôi cánh) ➔ Xem lại kiến thức đã học để ghi nhớ bền sâu ➔ Ôn tập.",
    "预习": "Ghép từ: 预 (Trước thời hạn) + 习 (Tập tành nghiên cứu) ➔ Đọc trước nội dung bài giảng trước khi lên lớp ➔ Soạn bài, chuẩn bị trước.",
    "总共": "Ghép từ: 总 (Gom hết mọi mối tơ) + 共 (Chung một khối) ➔ Hợp toàn bộ số lượng lại thành con số tổng ➔ Tổng cộng.",
    "词": "Chiết tự: Ngôn 讠 (lời nói) + Ty 司 (điều hành khuôn phép) ➔ Đơn vị từ ngữ có nghĩa hoàn chỉnh trong ngữ pháp ➔ Từ vựng, lời lẽ.",
    "语法": "Ghép từ: 语 (Ngôn ngữ) + 法 (Pháp: quy tắc phép tắc chuẩn mực) ➔ Hệ thống quy tắc cấu tạo câu đúng chuẩn ➔ Ngữ pháp.",
    "句子": "Ghép từ: 句 (Khẩu miệng nói tròn vành rõ nghĩa) + 子 ➔ Chuỗi từ kết hợp diễn đạt trọn vẹn một ý nghĩ ➔ Câu văn.",
    "水平": "Ghép từ: 水 (Mực nước phẳng lặng dâng cao) + 平 (Cân bằng không chênh lệch) ➔ Thước đo chuẩn mực năng lực của người học ➔ Trình độ, đẳng cấp.",
    "提高": "Ghép từ: 提 (Thủ 扌 nâng bổng lên) + 高 (Vươn lên tầm cao mới) ➔ Nâng tầm hiểu biết và kỹ năng lên nấc thang mới ➔ Nâng cao, cải thiện.",
    "简单": "Ghép từ: 简 (Thẻ tre viết ngắn gọn) + 单 (Đơn nhất, rõ ràng) ➔ Rõ ràng ngắn gọn không hề rối rắm ➔ Đơn giản, dễ hiểu.",
    "复杂": "Ghép từ: 复 (Nhiều tầng lớp) + 杂 (Trộn lẫn nhiều màu sắc tơ) ➔ Nhiều yếu tố đan xen chằng chịt khó gỡ ➔ Phức tạp, rắc rối.",
    "清楚": "Ghép từ: 清 (Nước 氵 trong veo nhìn tận đáy) + 楚 (Rừng cây Sở ngay hàng thẳng lối) ➔ Rành mạch sáng sủa không chút mơ hồ ➔ Rõ ràng, minh bạch.",
    "明白": "Ghép từ: 明 (Nhật Nguyệt soi rạng) + 白 (Trắng ngần sáng tỏ) ➔ Đầu óc thông suốt thấu triệt mọi ngóc ngách ➔ Hiểu rõ, thông suốt.",
    "流利": "Ghép từ: 流 (Nước 氵 chảy xiết tuôn trào) + 利 (Lưỡi dao Đao 刂 bén ngót ngọt xớt) ➔ Nói năng lưu loát trôi chảy như suối reo ➔ Lưu loát, trôi chảy.",
    "成功": "Ghép từ: 成 (Hoàn thành viên mãn) + 功 (Công sức Lực gặt hái thành tựu) ➔ Gặt hái trái ngọt sau chuỗi ngày nỗ lực bền bỉ ➔ Thành công.",
    "相信": "Ghép từ: 相 (Đối diện nhìn nhận nhau) + 信 (Lời nói của con người giữ trọn chữ tín) ➔ Đặt trọn niềm tin không mảy may nghi ngờ ➔ Tin tưởng, tin cậy.",
    "加油": "Ghép từ: 加 (Gia tăng sức mạnh Lực) + 油 (Đổ thêm dầu vào lửa cho bùng cháy) ➔ Khẩu hiệu cổ vũ dồn toàn lực tiến lên ➔ Cố lên! (Thêm dầu).",
    "开始": "Ghép từ: 开 (Mở toang cánh cổng) + 始 (Người phụ nữ Nữ mang thai thai nghén bắt đầu) ➔ Khởi động bước đi đầu tiên của hành trình ➔ Bắt đầu, khởi sự.",
    "结束": "Ghép từ: 结 (Mịch 纟 buộc thắt nút dây gọn gàng) + 束 (Bó lại thành bó) ➔ Buộc nút hoàn tất mọi công đoạn ➔ Kết thúc, khép lại.",
    "时间": "Ghép từ: 时 (Mặt trời Nhật dịch chuyển theo giờ) + 间 (Khoảng không giữa hai mốc) ➔ Dòng chảy vô tận của cuộc sống ➔ Thời gian.",
    "分": "Chiết tự: Bát 八 + Đao 刀 (chia phần từng thang điểm) ➔ Điểm số đánh giá trong kỳ thi; phút đồng hồ ➔ Điểm số; phút.",
    "题": "Chiết tự: Thị 是 (chân lý đúng đắn) + Hiệt 页 (trang giấy thi) ➔ Câu hỏi in trên đề bài sát hạch ➔ Câu hỏi, đề bài.",
    "选": "Chiết tự: Xước 辶 (bước chân) + Tiên 先 (đi trước nhắm trúng) ➔ Cân nhắc nhắm trúng phương án tối ưu nhất ➔ Lựa chọn, chọn.",
    "正确": "Ghép từ: 正 (Ngay ngắn thẳng thắn) + 确 (Thạch 石 kiên cố vững vàng chân lý) ➔ Hoàn toàn chuẩn xác không có sai sót ➔ Chính xác, đúng đắn.",
    "完全": "Ghép từ: 完 (Ngôi nhà Miên trọn vẹn) + 全 (Viên ngọc Vương không tì vết) ➔ Đầy đủ 100% không thiếu sót điều gì ➔ Hoàn toàn, trọn vẹn.",
    "通过": "Ghép từ: 通 (Thông suốt bốn phương) + 过 (Băng qua cửa ải) ➔ Vượt qua kỳ thi sát hạch để nhận chứng chỉ danh giá ➔ Vượt qua, đậu kỳ thi."
  }
};
