export const LESSONS_2_TO_6 = {
  // ================= BÀI 2 =================
  2: {
    "叫": "Chiết tự: Bộ Khẩu 口 (miệng) + Khảm 丩 (dây buộc, cuộn lại) ➔ Miệng mở ra gọi to tên ai đó ➔ Gọi là, tên là.",
    "姓": "Chiết tự: Bộ Nữ 女 (phụ nữ, mẹ) + Sinh 生 (sinh nở) ➔ Thời thị tộc cổ con sinh ra mang họ mẹ ➔ Họ (trong họ tên).",
    "名字": "Ghép từ: 名 (Tịch 夕 trời tối + Khẩu 口: tối không thấy mặt phải gọi tên nhau) + 字 (Mái nhà 宀 nuôi dạy con 子 học chữ) ➔ Tên gọi của một người.",
    "什么": "Ghép từ: 什 (Nhân 亻 + Thập 十: mười người cùng hỏi nhau) + 么 (dáng vẻ thắc mắc) ➔ Cái gì, câu hỏi khi chưa rõ sự vật.",
    "是": "Chiết tự: Nhật 日 (mặt trời) + Sơ 疋/正 (ngay thẳng) ➔ Mặt trời soi sáng sự thật hiển nhiên, không thể chối cãi ➔ Là, đúng, phải.",
    "不": "Chiết tự: Hình ảnh mầm cây nằm dưới mặt đất chưa thể vươn lên nở hoa ➔ Mang ý phủ định, chưa được ➔ Không, chẳng.",
    "人": "Chiết tự: Hình ảnh con người nhìn nghiêng với hai chân đang sải bước vững chãi ➔ Con người, nhân loại.",
    "国": "Chiết tự: Bộ Vi 囗 (tường thành bao quanh bờ cõi) bảo vệ viên Ngọc 玉 quý giá bên trong ➔ Quốc gia, đất nước.",
    "国家": "Ghép từ: 国 (Đất nước) + 家 (Mái nhà của muôn dân) ➔ Tổ quốc, đất nước, quê hương.",
    "越南": "Cầu nối Hán-Việt: 越 (Vượt qua ngàn gian nan để vươn lên) + 南 (Phương Nam ngập tràn ánh nắng) ➔ Đất nước Việt Nam kiên cường.",
    "中国": "Ghép từ: 中 (Trung tâm vũ trụ) + 国 (Đất nước) ➔ Đất nước nằm ở vùng bình nguyên trung tâm ➔ Trung Quốc.",
    "美国": "Ghép từ: 美 (Dương 羊 con cừu + Đại 大 to béo là biểu tượng của vẻ đẹp) + 国 (Nước) ➔ Đất nước Hoa Kỳ xinh đẹp.",
    "日本": "Ghép từ: 日 (Mặt trời) + 本 (Gốc rễ cây Mộc 木 có gạch chỉ nơi phát tích) ➔ Nơi cội nguồn mặt trời mọc rạng đông ➔ Nhật Bản.",
    "韩国": "Ghép từ: 韩 (Hàn: thành quách kiên cố) + 国 (Quốc gia) ➔ Đất nước Hàn Quốc.",
    "英国": "Ghép từ: 英 (Anh: hoa thảo mộc 艹 ngát hương, tài hoa xuất chúng) + 国 (Quốc) ➔ Nước Anh.",
    "哪": "Chiết tự: Bộ Khẩu 口 (miệng hỏi) + Na 那 (kia, đó) ➔ Mở miệng hỏi 'ở đằng kia là người nơi nào?' ➔ Nào, đâu.",
    "谁": "Chiết tự: Ngôn 讠 (lời nói) + Chuy 隹 (chim đuôi ngắn) ➔ Tiếng chim ríu rít như tiếng ai thì thầm hỏi 'ai đó?' ➔ Ai (đại từ hỏi người).",
    "朋友": "Chiết tự: 朋 (Hai vầng trăng 月 月 song hành cùng soi sáng) + 友 (Hai bàn tay đan chặt tương trợ) ➔ Người tri kỷ kề vai sát cánh ➔ Bạn bè.",
    "的": "Chiết tự: Bạch 白 (màu trắng) + Thược 勺 (cái muỗng múc) ➔ Tấm bia ngắm màu trắng ➔ Trợ từ kết cấu chỉ sở hữu: của.",
    "老师": "Chiết tự: 老 (Lão: người già tóc dài chống gậy đức cao vọng trọng) + 师 (Sư: người dẫn đường quân đội) ➔ Bậc tiền bối dẫn dắt tri thức ➔ Thầy cô giáo.",
    "学生": "Ghép từ: 学 (Mái nhà học vấn có bảng chữ) + 生 (Sinh sôi, trưởng thành) ➔ Người trẻ tuổi tiếp thu tri thức để lớn khôn ➔ Học sinh, sinh viên.",
    "留学生": "Ghép từ: 留 (Lưu lại nơi đất khách) + 学 (Học) + 生 (Sinh viên) ➔ Người lưu lại nước ngoài để theo đuổi con đường học tập ➔ Du học sinh.",
    "认识": "Chiết tự: 认 (Ngôn 讠 + Nhân 人) + 识 (Ngôn 讠 + Chỉ 只) ➔ Dùng lời nói trò chuyện để hiểu rõ về đối phương ➔ Quen biết, nhận diện.",
    "高兴": "Ghép từ: 高 (Lầu son gác tía cao vút) + 兴 (Bốn tay cùng nâng cao hào hứng) ➔ Tâm trạng phấn chấn dâng trào ➔ Vui vẻ, hào hứng.",
    "吗": "Chiết tự: Bộ Khẩu 口 (miệng hỏi) + Mã 马 (ngựa, lấy âm mǎ ➔ ma) ➔ Mở miệng hỏi xác nhận lại thông tin ➔ Phải không, à, hả."
  },

  // ================= BÀI 3 =================
  3: {
    "家": "Chiết tự: Mái nhà Miên 宀 che chở cho con Heo Thỉ 豕 nuôi bên dưới ➔ Hình ảnh mái ấm no đủ thời xưa ➔ Gia đình, ngôi nhà.",
    "有": "Chiết tự: Bàn tay trái 𠂇 đang nâng giữ một tảng thịt Nguyệt/Nhục 月 ➔ Trong tay nắm giữ đồ vật giá trị ➔ Có, sở hữu.",
    "没有": "Ghép từ: 没 (Ba chấm thủy 氵 trôi dạt biến mất) + 有 (Có) ➔ Của cải đã trôi sạch không còn gì ➔ Không có, chưa có.",
    "口": "Chiết tự: Hình vẽ một chiếc miệng mở rộng ➔ Cái miệng, dùng làm lượng từ đếm số nhân khẩu trong gia đình.",
    "几": "Chiết tự: Hình chiếc bàn nhỏ kê góc nhà, nét mảnh khảnh biểu thị số lượng nhỏ ➔ Mấy (thường dùng khi đếm dưới 10).",
    "岁": "Chiết tự: Bộ Sơn 山 (ngọn núi) trên bộ Tịch 夕 (đêm tối) ➔ Trải qua bao mùa trăng lên đỉnh núi là thêm một tuổi đời ➔ Tuổi.",
    "今年": "Ghép từ: 今 (Hiện tại, ngay lúc này) + 年 (Năm) ➔ Năm hiện tại chúng ta đang sống ➔ Năm nay.",
    "多大": "Ghép từ: 多 (Nhiều) + 大 (Lớn) ➔ Đã lớn được bao nhiêu rồi? ➔ Mẫu câu hỏi tuổi tác thân mật: Bao nhiêu tuổi.",
    "爸爸": "Chiết tự: Bộ Phụ 父 (người cha cầm roi dạy bảo nghiêm khắc) + Ba 巴 (lấy âm bā) ➔ Người cha thân thương trụ cột gia đình ➔ Bố, cha.",
    "妈妈": "Chiết tự: Bộ Nữ 女 (người phụ nữ dịu dàng) + Mã 马 (ngựa, lấy âm mǎ ➔ mā) ➔ Người phụ nữ tần tảo gánh vác việc nhà vì con ➔ Mẹ, má.",
    "哥哥": "Chiết tự: Hai chữ Khả 可 chồng lên nhau biểu thị người có thể gánh vác nhiều trách nhiệm nặng nhọc ➔ Anh trai.",
    "姐姐": "Chiết tự: Bộ Nữ 女 (con gái) + Thả 且 (bệ đá trang trọng) ➔ Người con gái lớn được tôn kính trong nhà ➔ Chị gái.",
    "弟弟": "Chiết tự: Hình sợi dây cuộn tròn quanh trục cọc gỗ ngắn nhỏ ➔ Đứa em bé nhỏ luôn được anh chị bảo bọc ➔ Em trai.",
    "妹妹": "Chiết tự: Bộ Nữ 女 (con gái) + Vị 未 (chưa trưởng thành, cành cây còn non) ➔ Đứa em gái nhỏ chưa đến tuổi cập kê ➔ Em gái.",
    "儿子": "Ghép từ: 儿 (Đứa trẻ đang chập chững bước đi) + 子 (Đứa con thơ) ➔ Đứa con trai yêu quý trong gia đình ➔ Con trai.",
    "女儿": "Ghép từ: 女 (Nữ: người con gái) + 儿 (Con cái) ➔ Đứa con gái ruột thịt ngoan ngoãn ➔ Con gái.",
    "爷爷": "Chiết tự: Bộ Phụ 父 (người cha) + Da 耶 (tai to phúc hậu) ➔ Người cha phúc hậu sinh ra cha mình ➔ Ông nội.",
    "奶奶": "Chiết tự: Bộ Nữ 女 (phụ nữ) + Nãi 乃 (ngực cho con bú) ➔ Người phụ nữ lớn tuổi đức độ dòng họ ➔ Bà nội.",
    "孩子": "Ghép từ: 孩 (Tử 子 + Hợi 亥: đứa trẻ sơ sinh) + 子 (Con trẻ) ➔ Trẻ con, con cái trong nhà.",
    "零": "Chiết tự: Mưa Vũ 雨 rơi trên lệnh Lệnh 令 ➔ Giọt mưa lất phất sót lại chẳng đáng là bao ➔ Số không (0), số lẻ.",
    "一": "Chiết tự: Một nét ngang duy nhất vạch ngang đất trời ➔ Khởi nguồn của vạn vật ➔ Số 1.",
    "两": "Chiết tự: Cái cân đòn có hai quả cân hai bên thăng bằng ➔ Cặp đôi, hai (thường đứng trước lượng từ).",
    "十": "Chiết tự: Một nét ngang một nét dọc giao nhau trọn vẹn mọi phương hướng ➔ Sự thập toàn thập mỹ ➔ Số 10.",
    "百": "Chiết tự: Chữ Nhất 一 đặt trên chữ Bạch 白 ➔ Đếm rõ ràng rành mạch đến một trăm ➔ Số 100, trăm.",
    "了": "Chiết tự: Hình đứa bé vừa được bọc tã chào đời ➔ Sự việc đã hoàn tất, biến đổi trạng thái mới ➔ Rồi (trợ từ ngữ khí)."
  },

  // ================= BÀI 4 =================
  4: {
    "今天": "Ghép từ: 今 (Ngay thời điểm này) + 天 (Bầu trời, ngày) ➔ Ngày hôm nay ta đang hiện diện ➔ Hôm nay.",
    "明天": "Ghép từ: 明 (Nhật 日 mặt trời + Nguyệt 月 mặt trăng kết hợp tỏa sáng) + 天 (Ngày) ➔ Ngày mai tươi sáng đang đến ➔ Ngày mai.",
    "昨天": "Chiết tự: 日 (Mặt trời) + Tạc 乍 (vừa mới trôi qua) + 天 (Ngày) ➔ Vầng thái dương vừa mới lặn hôm trước ➔ Hôm qua.",
    "年": "Chiết tự: Bắt nguồn từ hình người gánh bó lúa trĩu hạt mừng vụ mùa kết thúc sau 365 ngày ➔ Năm, niên.",
    "月": "Chiết tự: Hình vẽ vầng trăng khuyết soi sáng bầu trời đêm theo chu kỳ 30 ngày ➔ Tháng, mặt trăng.",
    "日": "Chiết tự: Hình vẽ mặt trời tròn trịa có đốm đen ở trung tâm ➔ Ngày, mặt trời.",
    "号": "Chiết tự: Bộ Khẩu 口 (miệng hô to) + Cái 丂 (cất tiếng) ➔ Hô vang số hiệu, con số ➔ Ngày (khẩu ngữ), mã số.",
    "星期": "Ghép từ: 星 (Ngôi sao tinh tú) + 期 (Kỳ hạn, chu kỳ) ➔ Chu kỳ tính theo các vì sao dịch chuyển ➔ Tuần lễ, thứ trong tuần.",
    "星期一": "Ghép từ: 星期 (Tuần) + 一 (Số 1) ➔ Ngày đầu tiên bắt đầu tuần mới làm việc ➔ Thứ Hai.",
    "星期天": "Ghép từ: 星期 (Tuần) + 天 (Trời) ➔ Ngày của ông trời ban tặng để nghỉ ngơi ➔ Chủ Nhật.",
    "周末": "Ghép từ: 周 (Chu kỳ tròn một tuần) + 末 (Điểm tận cùng, cuối ngọn cây) ➔ Điểm cuối cùng khép lại tuần lễ ➔ Cuối tuần.",
    "生日": "Ghép từ: 生 (Sinh ra, chào đời) + 日 (Ngày) ➔ Ngày thiêng liêng mình cất tiếng khóc chào đời ➔ Sinh nhật.",
    "去": "Chiết tự: Thổ 土 (mảnh đất cũ) bên trên bộ Khư 厶 (bước đi rời xa) ➔ Rời bỏ mảnh đất cũ để đi đến nơi mới ➔ Đi, đến.",
    "来": "Chiết tự: Hình cây lúa mì đung đưa từ phương xa đưa hạt giống tới ➔ Hướng về phía người nói ➔ Đến, lại đây.",
    "学校": "Ghép từ: 学 (Học hành) + 校 (Mộc 木 cây cọc dựng trường + Giao 交 giao lưu kết bạn) ➔ Nơi giao lưu học hỏi tri thức ➔ Trường học.",
    "看": "Chiết tự: Bàn tay Thủ 手 che trên đôi mắt Mục 目 để nhìn xa xăm ➔ Nhìn, ngắm, xem, đọc.",
    "书": "Chiết tự: Cây bút đang chấm mực viết lên thẻ tre lưu giữ tri thức ➔ Cuốn sách, văn thư.",
    "什么时候": "Ghép từ: 什么 (Cái gì) + 时候 (Thời điểm, khắc giờ) ➔ Lúc nào, thời điểm nào, khi nào.",
    "节": "Chiết tự: Thảo 艹 (cỏ cây) + Tiết 卩 (đốt tre, mắt ngấn) ➔ Từng mắt tre phân chia các khoảng thời gian ➔ Tiết học, ngày lễ tết.",
    "节日": "Ghép từ: 节 (Dịp kỷ niệm) + 日 (Ngày) ➔ Ngày lễ hội, tết vui tươi trong năm.",
    "买": "Chiết tự: Lưới võng bên trên vỏ sò Bối 贝 (tiền tệ cổ xưa) ➔ Tung tiền ra để thu gom hàng hóa về ➔ Mua sắm.",
    "做": "Chiết tự: Bộ Nhân đứng 亻 (con người) + Cố 故 (sự việc cũ) ➔ Con người bắt tay bắt chân vào hành động tạo ra sản phẩm ➔ Làm, chế tạo.",
    "工作": "Ghép từ: 工 (Thước đo vuông góc của người thợ) + 作 (Nhân 亻 + Sạ 乍: con người bắt đầu bắt tay tạo tác) ➔ Nghề nghiệp, làm việc.",
    "休息": "Chiết tự: 休 (Nhân 亻 đứng tựa gốc cây Mộc 木 giải lao) + 息 (Tự 自 mũi hít thở đều + Tâm 心 thư thái) ➔ Ngừng làm việc để nạp lại năng lượng ➔ Nghỉ ngơi.",
    "听": "Chiết tự: Bộ Khẩu 口 (tai lắng nghe theo khẩu lệnh) + Cân 斤 (cái rìu nhạy bén sắc bén) ➔ Lắng tai đón nhận âm thanh ➔ Nghe."
  },

  // ================= BÀI 5 =================
  5: {
    "现在": "Ghép từ: 现 (Ngọc quý 王 xuất hiện rõ ràng 见) + 在 (Đang tồn tại) ➔ Khoảnh khắc đang hiện hữu ngay trước mắt ➔ Bây giờ, hiện tại.",
    "点": "Chiết tự: Chiếm 占 (xem bói chia vạch) + Bốn chấm hỏa 灬 (từng chấm lửa tí tách rơi) ➔ Từng giọt thời gian rơi điểm ➔ Giờ đồng hồ, chấm nhỏ.",
    "分": "Chiết tự: Bát 八 (tách ra hai bên) + Đao 刀 (con dao sắc) ➔ Dùng dao chia nhỏ thời gian ra từng phần ➔ Phút, chia phần.",
    "半": "Chiết tự: Bát 八 (tách đôi) con bò Ngưu 牛 bằng nhát chém chính giữa ➔ Một nửa, rưỡi (30 phút).",
    "刻": "Chiết tự: Hợi 亥 + Đao 刂 (con dao khắc vạch lên đồng hồ nước cổ) ➔ Mỗi vạch khắc ứng với đúng 15 phút ➔ Khắc (15 phút).",
    "差": "Chiết tự: Dương 羊 (con cừu sừng lệch) + Tả 左 (tay trái) ➔ Sự so le, chưa khớp chuẩn ➔ Kém (trong cách nói giờ kém), thiếu.",
    "早上": "Ghép từ: 早 (Mặt trời Nhật 日 nhô lên khỏi vạch mốc Thập 十) + 上 (Phía trên) ➔ Buổi sáng sớm rạng đông.",
    "上午": "Ghép từ: 上 (Trước) + 午 (Giờ Ngọ 12h trưa) ➔ Khoảng thời gian trước buổi trưa (8h - 11h30) ➔ Buổi sáng.",
    "中午": "Ghép từ: 中 (Chính giữa) + 午 (Giờ Ngọ) ➔ Đúng giữa đỉnh điểm ban ngày lúc 12h trưa ➔ Buổi trưa.",
    "下午": "Ghép từ: 下 (Sau) + 午 (Giờ Ngọ) ➔ Khoảng thời gian sau 12h trưa bóng nghiêng về tây ➔ Buổi chiều.",
    "晚上": "Ghép từ: 晚 (Mặt trời 日 biến mất 免 buông màn đêm) + 上 (Buổi) ➔ Buổi tối sau khi trời lặn.",
    "夜里": "Ghép từ: 夜 (Màn đêm buông bóng người bước đi) + 里 (Bên trong) ➔ Giữa đêm khuya thanh vắng.",
    "起床": "Ghép từ: 起 (Chạy bộ Tẩu 走 đứng dậy) + 床 (Giường ngủ) ➔ Rời khỏi chiếc giường êm ấm để bắt đầu ngày mới ➔ Thức dậy.",
    "刷牙": "Ghép từ: 刷 (Cầm chổi quét sạch bụi) + 牙 (Chiếc răng ngà ngà) ➔ Cầm bàn chải cọ sạch từng kẽ răng ➔ Đánh răng.",
    "洗脸": "Ghép từ: 洗 (Nước 氵 rửa sạch mũi chân) + 脸 (Nhục 月 da thịt + Thiêm 佥 khuôn mặt) ➔ Dùng nước mát rửa sạch mặt mũi ➔ Rửa mặt.",
    "洗澡": "Chiết tự: 洗 (Nước 氵 rửa ráy) + 澡 (Nước 氵 dội lên thân cây có đàn chim hót ríu rít) ➔ Tắm táp sạch sẽ mát rượi ➔ Tắm rửa.",
    "睡觉": "Chiết tự: 睡 (Mục 目 đôi mắt rũ xuống vì mệt Thùy 垂) + 觉 (Nhìn Kiến 见 thấy nhẹ nhõm) ➔ Khép mi chìm vào giấc mơ êm đềm ➔ Đi ngủ.",
    "吃饭": "Ghép từ: 吃 (Miệng 口 nhai đồ ăn) + 饭 (Thực 饣 thức ăn chế biến từ phản hồi hạt gạo) ➔ Ăn cơm, dùng bữa.",
    "回": "Chiết tự: Hai vòng thành vuông lồng vào nhau xoay tròn trở về tâm điểm ➔ Quay trở lại nơi xuất phát ➔ Về, quay lại.",
    "到": "Chiết tự: Chí 至 (mũi tên bắn cắm phập tới đích) + Đao 刂 ➔ Đã chạm tới mốc đến mong muốn ➔ Đến nơi, tới.",
    "前": "Chiết tự: Chiếc thuyền Chu 舟 rẽ nước tiến thẳng về phía trước ➔ Đằng trước, trước khi.",
    "后": "Chiết tự: Người đi theo sau gót chân của thủ lĩnh ➔ Phía sau, sau khi.",
    "小时": "Ghép từ: 小 (Nhỏ bé) + 时 (Thời gian tính bằng mặt trời Nhật 日) ➔ Một đơn vị đo thời gian tiêu chuẩn ➔ Tiếng đồng hồ, giờ đồng hồ.",
    "分钟": "Ghép từ: 分 (Chia nhỏ) + 钟 (Chiếc chuông đồng hồ điểm nhịp) ➔ Từng nhịp quay của kim phút ➔ Phút đồng hồ.",
    "有时候": "Ghép từ: 有 (Có) + 时候 (Thời điểm) ➔ Có những khoảnh khắc diễn ra không thường xuyên ➔ Thỉnh thoảng, đôi khi."
  },

  // ================= BÀI 6 =================
  6: {
    "吃": "Chiết tự: Bộ Khẩu 口 (cái miệng) + Khất 乞 (xin ăn) ➔ Mở miệng đón nhận thức ăn ngon lành ➔ Ăn.",
    "喝": "Chiết tự: Bộ Khẩu 口 (cái miệng) + Hạt 曷 (trời nắng gắt cần giải khát) ➔ Miệng khô khát cần đưa chất lỏng vào cổ họng ➔ Uống.",
    "茶": "Chiết tự: Thảo 艹 (búp lá non) hái trên cây Mộc 木 có người Nhân 人 thưởng thức tao nhã ➔ Trà, chè xanh.",
    "水": "Chiết tự: Dòng suối uốn lượn tuôn trào bọt nước trắng xóa ở giữa ➔ Nước, dòng nước.",
    "咖啡": "Từ tượng thanh mượn âm Coffee: Cả hai chữ đều có bộ Khẩu 口 biểu thị đồ uống sành điệu qua đường miệng ➔ Cà phê.",
    "牛奶": "Ghép từ: 牛 (Ngưu: con bò sữa có đôi sừng) + 奶 (Nãi: bầu sữa mẹ ngọt ngào) ➔ Dòng sữa dinh dưỡng từ con bò ➔ Sữa bò.",
    "米饭": "Ghép từ: 米 (Hạt thóc nứt vỏ tỏa ra 4 phương) + 饭 (Bộ Thực 饣 thức ăn) ➔ Bát cơm gạo trắng dẻo thơm ➔ Cơm trắng.",
    "面条": "Ghép từ: 面 (Bột mì nghiền mịn) + 条 (Sợi thon dài) ➔ Từng sợi mì dẻo dai dài mượt ➔ Mì sợi, bát mì.",
    "包子": "Chiết tự: 包 (Hình bọc tã ủ kín nhân thịt thơm phức) + 子 (Đồ vật nhỏ) ➔ Bánh bao vỏ trắng nhân thịt bốc khói ➔ Bánh bao.",
    "饺子": "Chiết tự: Thực 饣 (thức ăn) + Giao 交 (giao nhau) ➔ Món bánh ăn vào khoảnh khắc giao thừa giữa năm cũ và năm mới ➔ Bánh sủi cảo.",
    "菜": "Chiết tự: Thảo 艹 (rau cỏ trên đất) được bàn tay Móng 爫 hái mang lên giá gỗ Mộc 木 xào nấu ➔ Món ăn, rau củ.",
    "肉": "Chiết tự: Miếng thịt tươi có các thớ gân sọc chéo đan xen bên trong ➔ Thịt động vật.",
    "鱼": "Chiết tự: Hình vẽ con cá với đầu nhọn, thân vảy lấp lánh và vây đuôi uốn lượn dưới nước ➔ Con cá.",
    "鸡蛋": "Ghép từ: 鸡 (Kê: gà có lông mào) + 蛋 (Trứng có vỏ bảo vệ con côn trùng sơ sinh) ➔ Quả trứng gà tròn bổ dưỡng.",
    "水果": "Ghép từ: 水 (Nước mọng nước) + 果 (Trái cây trĩu trên cành Mộc 木) ➔ Trái cây tươi ngọt mọng nước ➔ Hoa quả, trái cây.",
    "苹果": "Chiết tự: Bình 苹 (Thảo 艹 + Bình 平 bình an) + Quả 果 (trái cây) ➔ Loại trái cây mang biểu tượng cầu chúc bình an ➔ Quả táo tây.",
    "好吃": "Ghép từ: 好 (Tốt lành, tuyệt vời) + 吃 (Ăn) ➔ Món ăn đưa vào miệng thấy khoái khẩu tuyệt vời ➔ Ngon miệng (đồ ăn).",
    "好喝": "Ghép từ: 好 (Tuyệt vời) + 喝 (Uống) ➔ Nước uống ngụm nào sảng khoái mát lành ngụm ấy ➔ Ngon, dễ uống (đồ uống).",
    "甜": "Chiết tự: Cam 甘 (vị ngọt nơi đầu lưỡi) + Thiệt 舌 (chiếc lưỡi nếm thử mật ong) ➔ Hương vị ngọt ngào như đường mật ➔ Ngọt.",
    "辣": "Chiết tự: Tân 辛 (vị cay nồng xé lưỡi) + Thúc 束 (bó ớt cay xè chụm lại) ➔ Vị cay xè bùng nổ trong khoang miệng ➔ Cay nồng.",
    "饱": "Chiết tự: Thực 饣 (đồ ăn) + Bao 包 (no tròn căng bụng) ➔ Ăn uống no nê căng cả bụng ➔ No bụng.",
    "饿": "Chiết tự: Thực 饣 (đồ ăn) + Ngã 我 (bản thân tôi) ➔ Cái bụng tôi đang réo ùng ục đòi ăn ➔ Đói bụng.",
    "饭馆": "Ghép từ: 饭 (Cơm nước ăn uống) + 馆 (Tòa nhà lớn đón tiếp thực khách) ➔ Quán ăn, nhà hàng ẩm thực.",
    "菜单": "Ghép từ: 菜 (Các món ăn) + 单 (Tờ giấy đơn liệt kê danh sách) ➔ Tờ danh sách các món ăn để chọn ➔ Thực đơn, Menu.",
    "服务员": "Ghép từ: 服务 (Phục vụ khách hàng tận tâm) + 员 (Thành viên, nhân sự có thẻ) ➔ Nhân viên phục vụ bàn, bồi bàn."
  }
};
