export const LESSONS_12_TO_16 = {
  // ================= BÀI 12 =================
  12: {
    "在": "Chiết tự: Thổ 土 (mặt đất màu mỡ) + Tài 才 (hạt mầm bắt rễ) ➔ Mầm non bén rễ đứng vững chãi trên mảnh đất ➔ Ở, tại; đang diễn ra.",
    "哪儿": "Ghép từ: 哪 (Mở miệng hỏi phương nào) + 儿 (Hậu tố ngữ âm Bắc Kinh) ➔ Đang hỏi vị trí phương hướng ➔ Ở đâu, chỗ nào.",
    "哪里": "Ghép từ: 哪 (Hỏi vị trí) + 里 (Bên trong, vùng đất) ➔ Mẫu từ hỏi địa điểm phổ biến toàn Trung Quốc ➔ Ở đâu, nơi nào.",
    "这儿": "Ghép từ: 这 (Gần sát chân) + 儿 (Hậu tố vị trí) ➔ Ngay tại vị trí người nói đang đứng ➔ Ở đây, chỗ này.",
    "这里": "Ghép từ: 这 (Chỗ này) + 里 (Bên trong vùng) ➔ Không gian xung quanh người nói ➔ Nơi này, chốn này.",
    "那儿": "Ghép từ: 那 (Ở phía xa tầm mắt) + 儿 ➔ Địa điểm cách xa người nói ➔ Ở đằng kia, chỗ đó.",
    "那里": "Ghép từ: 那 (Phía xa) + 里 (Nơi chốn) ➔ Vị trí xác định ở khoảng cách xa ➔ Nơi đó, chỗ ấy.",
    "前面": "Ghép từ: 前 (Chiếc thuyền rẽ sóng đi trước) + 面 (Bề mặt, hướng diện) ➔ Phía ngay trước mặt mình ➔ Phía trước, đằng trước.",
    "后面": "Ghép từ: 后 (Bước sau chân thủ lĩnh) + 面 (Phương diện) ➔ Phía sau lưng của mình ➔ Phía sau, đằng sau.",
    "左": "Chiết tự: Tay trái 𠂇 cầm cây thước thợ 工 đo đạc bên mạn trái ➔ Bên trái, tả.",
    "左边": "Ghép từ: 左 (Phía trái) + 边 (Biên giới, rìa cạnh) ➔ Khu vực nằm về mạn tay trái ➔ Phía bên trái.",
    "右": "Chiết tự: Tay phải 𠂇 cầm chiếc thìa đưa thức ăn vào Khẩu 口 ➔ Phía tay thuận xúc cơm ➔ Bên phải, hữu.",
    "右边": "Ghép từ: 右 (Phía phải) + 边 (Bên cạnh) ➔ Khu vực nằm về mạn tay phải ➔ Phía bên phải.",
    "旁边": "Chiết tự: Bàng 旁 (trải rộng hai bên) + Biên 边 (rìa ngoài) ➔ Ngay sát vách cạnh sườn ➔ Bên cạnh, kề cận.",
    "中间": "Ghép từ: 中 (Đúng tâm điểm) + 间 (Khoảng không giữa hai cánh cửa) ➔ Vị trí chính giữa hai đầu ➔ Ở giữa, trung gian.",
    "东": "Chiết tự: Mặt trời Nhật 日 mọc xuyên qua tán cây Mộc 木 ở hướng ban mai ➔ Nơi bình minh chiếu rọi ➔ Hướng Đông.",
    "西": "Chiết tự: Hình tổ chim khi mặt trời lặn chim bay về tổ ngủ ➔ Phương hướng mặt trời lặn ➔ Hướng Tây.",
    "南": "Chiết tự: Nhạc khí bằng đồng treo dưới mái nhà ấm áp phương nam ➔ Phương trời ấm áp ➔ Hướng Nam.",
    "北": "Chiết tự: Hai người quay lưng 北 vào nhau run rẩy vì gió bấc lạnh giá ➔ Nơi đón gió lạnh từ cực bắc ➔ Hướng Bắc.",
    "远": "Chiết tự: Xước 辶 (bước chân đi) + Viên 袁 (vạt áo dài phất phơ) ➔ Càng đi bóng người càng xa tít tắp ➔ Xa xôi, cách trở.",
    "近": "Chiết tự: Xước 辶 (bước chân) + Cân 斤 (cái rìu gần gang tấc) ➔ Khoảng cách chỉ vài bước chân là tới nơi ➔ Gần gũi, sát bên.",
    "走": "Chiết tự: Thổ 土 (mảnh đất) + Sơ 疋 (bàn chân đạp lên) ➔ Đôi chân thoăn thoắt tiến bước trên đường ➔ Đi bộ, bước đi.",
    "路": "Chiết tự: Túc 足 (bàn chân) + Các 各 (mỗi người một ngả) ➔ Dấu chân muôn người đi qua lại tạo thành con đường ➔ Tuyến đường, con lộ."
  },

  // ================= BÀI 13 =================
  13: {
    "车": "Chiết tự: Hình vẽ nhìn từ trên xuống của chiếc xe ngựa kéo thời xưa có hai bánh và trục càng ➔ Xe cộ, phương tiện.",
    "坐": "Chiết tự: Hai người Nhân 人 ngồi đối diện trò chuyện trên mảnh đất Thổ 土 ➔ Đặt mông lên ghế, lên phương tiện ➔ Ngồi; đi (xe, tàu, máy bay).",
    "开车": "Ghép từ: 开 (Hai tay cầm vô lăng vận hành) + 车 (Xe) ➔ Thao tác điều khiển chiếc ô tô di chuyển ➔ Lái xe hơi.",
    "地铁": "Ghép từ: 地 (Dưới lòng đất) + 铁 (Đường ray bằng thép sắt) ➔ Tuyến tàu hỏa điện chạy ngầm sâu trong lòng phố ➔ Tàu điện ngầm.",
    "公交车": "Ghép từ: 公共 (Công cộng phục vụ muôn dân) + 交 (Giao thông) + 车 (Xe) ➔ Xe buýt lớn chở khách công cộng ➔ Xe buýt.",
    "出租车": "Ghép từ: 出租 (Cho thuê dịch vụ) + 车 (Xe) ➔ Phương tiện chở khách tính tiền theo đồng hồ cước ➔ Xe taxi.",
    "飞机": "Ghép từ: 飞 (Cánh chim sải cánh lượn bay trên trời) + 机 (Cỗ máy động cơ) ➔ Cỗ máy sắt bay lượn trên bầu trời xanh ➔ Máy bay.",
    "火车": "Ghép từ: 火 (Lò lửa than hừng hực bốc khói) + 车 (Đoàn toa tàu) ➔ Đoàn tàu chạy bằng động cơ đốt lửa hơi nước ➔ Tàu hỏa.",
    "站": "Chiết tự: Lập 立 (đứng nghiêm) + Chiêm 占 (chiếm lĩnh vị trí) ➔ Điểm dừng chân đón trả khách cố định ➔ Trạm, bến ga; đứng.",
    "机场": "Ghép từ: 飞机 (Máy bay) + 场 (Quảng trường rộng thênh thang) ➔ Bãi đất rộng lớn đón hạ cánh tàu bay ➔ Sân bay, phi trường.",
    "自行车": "Ghép từ: 自 (Tự mình) + 行 (Vận hành, di chuyển) + 车 (Chiếc xe đạp) ➔ Phương tiện tự dùng sức chân đạp để chạy ➔ Xe đạp.",
    "骑": "Chiết tự: Mã 马 (con ngựa) + Kỳ 奇 (ngồi dạng chân đặc biệt) ➔ Ngồi dạng chân cưỡi trên lưng thú hoặc yên xe ➔ Cưỡi, đạp xe.",
    "离": "Chiết tự: Cầm con dao chia cắt cự ly hai điểm ➔ Đo đạc khoảng cách giữa hai địa danh ➔ Cách (khoảng cách cự ly).",
    "从": "Chiết tự: Hai người Nhân 人 đi nối đuôi theo sau nhau từ điểm xuất phát ➔ Mốc điểm bắt đầu cuộc hành trình ➔ Từ (đâu đến đâu).",
    "往": "Chiết tự: Xích 彳 (bước chân) + Chủ 主 (ngọn nến soi đường) ➔ Nhắm thẳng mục tiêu phía trước mà tiến bước ➔ Hướng về, về phía.",
    "过": "Chiết tự: Xước 辶 (bước chân) + Thốn 寸 (từng tấc đường) ➔ Từng bước băng qua con đường, trải qua thời gian ➔ Đi qua, băng qua.",
    "停": "Chiết tự: Nhân 亻 (con người) + Đình 亭 (nghỉ chân tại quán đình) ➔ Tạm dừng bánh xe để nghỉ ngơi ➔ Dừng lại, đỗ xe.",
    "买票": "Ghép từ: 买 (Chi tiền mua) + 票 (Tấm vé lên tàu xe) ➔ Đổi tiền lấy vé hành trình hợp lệ ➔ Mua vé.",
    "上车": "Ghép từ: 上 (Bước lên) + 车 (Xe) ➔ Đặt chân lên sàn xe để bắt đầu chuyến đi ➔ Lên xe.",
    "下车": "Ghép từ: 下 (Bước xuống) + 车 (Xe) ➔ Rời khỏi khoang xe khi đến điểm dừng ➔ Xuống xe.",
    "路口": "Ghép từ: 路 (Con đường) + 口 (Cửa ngõ, chỗ giao cắt) ➔ Điểm giao cắt nơi các ngả đường gặp nhau ➔ Ngã tư, ngã ba, giao lộ."
  },

  // ================= BÀI 14 =================
  14: {
    "学习": "Chiết tự: 学 (Học hỏi dưới mái nhà tri thức) + 习 (Cánh chim non vỗ cánh tập bay) ➔ Học lý thuyết và rèn luyện thực hành ➔ Học tập.",
    "汉语": "Ghép từ: 汉 (Dân tộc Hán, sông Hán Thủy) + 语 (Ngôn 讠 lời nói từ Ngũ 五 Khẩu 口) ➔ Ngôn ngữ của dân tộc Hán ➔ Tiếng Trung, tiếng Hán.",
    "中文": "Ghép từ: 中 (Trung Hoa) + 文 (Hệ thống văn tự, nét chữ đẹp) ➔ Hệ thống văn tự và ngôn ngữ Trung Quốc ➔ Tiếng Trung, chữ Trung.",
    "字": "Chiết tự: Miên 宀 (mái nhà ấm) + Tử 子 (nuôi dạy con trẻ biết chữ) ➔ Ký tự văn tự ghi chép lại lời nói ➔ Chữ viết, từ đơn.",
    "汉字": "Ghép từ: 汉 (Người Hán) + 字 (Chữ viết) ➔ Hệ thống chữ tượng hình cổ truyền của Trung Hoa ➔ Chữ Hán.",
    "拼音": "Ghép từ: 拼 (Ghép các mảnh lại với nhau) + 音 (Âm thanh phát ra) ➔ Hệ chữ cái Latinh dùng ghép thanh mẫu vận mẫu ➔ Phiên âm Pinyin.",
    "说": "Chiết tự: Ngôn 讠 (lời nói) + Đoái 兑 (miệng cười vui vẻ) ➔ Mở miệng phát ra lời nói vui vẻ giao lưu ➔ Nói, phát biểu.",
    "读": "Chiết tự: Ngôn 讠 (lời nói) + Mại 卖 (nhả chữ lưu loát) ➔ Đọc to thành tiếng từng trang sách ➔ Đọc, xướng âm.",
    "写": "Chiết tự: Mịch 冖 (mái che nghiêng) + Nhất 一 bàn đặt tờ giấy cầm bút nắn nót ➔ Nắn nót từng nét mực trên trang giấy ➔ Viết chữ.",
    "难": "Chiết tự: Hựu 又 + Chuy 隹 (con chim mắc kẹt trong bẫy gai) ➔ Tình thế trắc trở nan giải khó gỡ ➔ Gian nan, khó khăn.",
    "容易": "Ghép từ: 容 (Dung nạp rộng lượng) + 易 (Nhật mặt trời + con thằn lằn đổi màu dễ dàng) ➔ Việc thuận lợi không chút phức tạp ➔ Dễ dàng, đơn giản.",
    "课": "Chiết tự: Ngôn 讠 (lời giảng giải) + Quả 果 (kết tinh hoa trái tri thức) ➔ Lời thầy cô truyền đạt trong từng buổi học ➔ Tiết học, bài học.",
    "上课": "Ghép từ: 上 (Bắt đầu bước vào) + 课 (Bài học) ➔ Chuông reo bắt đầu tiết học tập trung ➔ Vào lớp, đi học.",
    "下课": "Ghép từ: 下 (Khép lại kết thúc) + 课 (Bài học) ➔ Kết thúc giờ giảng để giải lao ➔ Tan học, hết giờ.",
    "本子": "Chiết tự: 本 (Gốc rễ thân cây bào thành giấy) + 子 ➔ Tập giấy đóng gáy dùng để ghi chép bài vở ➔ Quyển vở.",
    "笔": "Chiết tự: Trúc 竹 (cán bút bằng ống tre) + Mao 毛 (ngòi bút bằng lông thú) ➔ Cây bút lông chấm mực nắn nót chữ Hán ➔ Cây bút.",
    "懂": "Chiết tự: Tâm 忄 (con tim) + Đổng 董 (ngay thẳng thấu suốt) ➔ Trái tim và trí não thấu triệt bản chất vấn đề ➔ Hiểu, thấu hiểu.",
    "对": "Chiết tự: Hựu 又 + Thốn 寸 (chuẩn mực từng tấc gang tấc) ➔ Khớp hoàn toàn với chân lý chuẩn xác ➔ Đúng, chuẩn; đối xử.",
    "错": "Chiết tự: Kim 钅 (kim loại) + Tích 昔 (việc đã qua trắc trở) ➔ Mạ vàng bị lẫn tạp chất lệch chuẩn ➔ Sai lầm, lệch lạc.",
    "问题": "Ghép từ: 问 (Cất tiếng hỏi) + 题 (Đầu mục câu hỏi trên trang giấy) ➔ Điều thắc mắc hoặc bài toán cần giải quyết ➔ Câu hỏi, vấn đề.",
    "知道": "Ghép từ: 知 (Mũi tên Thỉ chỉ trúng miệng Khẩu: hiểu thấu) + 道 (Đạo lý, chân lý) ➔ Nắm rõ chân lý và ngọn ngành sự việc ➔ Biết, thấu hiểu.",
    "考试": "Ghép từ: 考 (Khảo sát trình độ) + 试 (Thử nghiệm tài năng) ➔ Kỳ sát hạch đánh giá kết quả học tập ➔ Thi cử, bài thi.",
    "练习": "Ghép từ: 练 (Mịch 纟 rèn luyện sợi tơ óng ả) + 习 (Tập bay nhiều lần) ➔ Ôn đi luyện lại để nhuần nhuyễn kỹ năng ➔ Luyện tập, bài tập.",
    "意思": "Ghép từ: 意 (Tâm tư ẩn sau âm thanh) + 思 (Bộ não Điền suy ngẫm trong tim Tâm) ➔ Ý nghĩa sâu xa hàm chứa trong từ ngữ ➔ Ý nghĩa; thú vị."
  },

  // ================= BÀI 15 =================
  15: {
    "上班": "Ghép từ: 上 (Bắt đầu) + 班 (Ca kíp, chia ngọc làm việc) ➔ Bước vào ca làm việc chính thức tại công sở ➔ Đi làm.",
    "下班": "Ghép từ: 下 (Rời khỏi) + 班 (Ca trực) ➔ Hoàn tất công việc trong ngày để về nhà ➔ Tan ca, tan sở.",
    "公司": "Ghép từ: 公 (Công cộng, minh bạch) + 司 (Quản lý điều hành) ➔ Tổ chức kinh doanh điều hành chung ➔ Công ty, doanh nghiệp.",
    "医生": "Ghép từ: 医 (Tủ chứa kim tiêm mũi tên chữa bệnh) + 生 (Bậc trí thức sinh ra cứu người) ➔ Người thầy thuốc cứu chữa bệnh nhân ➔ Bác sĩ.",
    "医院": "Ghép từ: 医 (Y thuật chữa bệnh) + 院 (Khu viện lớn có tường bao quanh) ➔ Cơ sở khám chữa bệnh quy mô ➔ Bệnh viện.",
    "护士": "Ghép từ: 护 (Tay Thủ bảo vệ che chở) + 士 (Bậc trí thức có tài) ➔ Thiên thần áo trắng tận tâm chăm sóc người ốm ➔ Y tá, điều dưỡng.",
    "司机": "Ghép từ: 司 (Điều khiển, nắm giữ) + 机 (Cỗ máy động cơ xe) ➔ Người cầm lái điều khiển phương tiện ➔ Tài xế, lái xe.",
    "经理": "Ghép từ: 经 (Kinh qua chỉ đạo) + 理 (Mài giũa viên ngọc trật tự) ➔ Người điều hành sắp xếp công việc trôi chảy ➔ Giám đốc, quản lý.",
    "办公室": "Ghép từ: 办公 (Làm việc công sự) + 室 (Căn phòng kín đáo) ➔ Phòng làm việc của cán bộ công chức ➔ Văn phòng làm việc.",
    "职员": "Ghép từ: 职 (Lắng tai Nhĩ nghe chỉ thị nghề nghiệp) + 员 (Thành viên có biên chế) ➔ Người làm công hưởng lương tại công ty ➔ Nhân viên.",
    "师傅": "Chiết tự: 师 (Bậc thầy giỏi nghề) + Phó 傅 (Truyền dạy kỹ năng) ➔ Danh xưng kính trọng dành cho thợ lành nghề, bác tài ➔ Bác tài, chú thợ.",
    "想": "Chiết tự: Tướng 相 (nhìn nhận đối tượng) + Tâm 心 (trái tim rung động) ➔ Trái tim luôn hướng về ai đó hoặc ấp ủ nguyện vọng ➔ Muốn, nhớ, suy nghĩ.",
    "当": "Chiết tự: Tiểu 小 + Khẩu 口 + Sơn 山 ➔ Đảm nhận gánh vác trọng trách chức vị ➔ Đảm nhiệm, làm (nghề nghiệp).",
    "有名": "Ghép từ: 有 (Có sẵn) + 名 (Tên tuổi vang danh) ➔ Ai ai khắp bốn phương cũng đều biết tên ➔ Nổi tiếng, trứ danh.",
    "累": "Chiết tự: Điền 田 (làm việc cày ruộng) + Mịch 糸 (bó tơ nặng trĩu trên lưng) ➔ Làm lụng cật lực cả ngày sức lực cạn kiệt ➔ Mệt mỏi, nhọc nhằn.",
    "挣钱": "Ghép từ: 挣 (Thủ 扌 ra sức dùng bàn tay) + 钱 (Tiền của) ➔ Đổ mồ hôi công sức lao động để có thu nhập ➔ Kiếm tiền.",
    "帮助": "Ghép từ: 帮 (Tấm vải Cân hỗ trợ bao bọc) + 助 (Dốc sức Lực cứu giúp người hoạn nạn) ➔ Chia sẻ khó khăn với người khác ➔ Giúp đỡ, hỗ trợ.",
    "帮": "Chiết tự: Dùng sức lực và vải vóc bảo bọc người khó khăn ➔ Chìa tay hỗ trợ trong cơn hoạn nạn ➔ Giúp, giúp sức.",
    "会": "Chiết tự: Nhân 人 (nhiều người) tụ họp dưới một mái nhà cùng thống nhất ➔ Nắm bắt kỹ năng; tụ họp ➔ Biết (qua học tập); cuộc họp.",
    "开会": "Ghép từ: 开 (Mở ra) + 会 (Hội nghị) ➔ Triệu tập các thành viên bàn bạc giải quyết sự vụ ➔ Họp, mở cuộc họp.",
    "事情": "Ghép từ: 事 (Sự việc cần giải quyết) + 情 (Tâm tình, hoàn cảnh) ➔ Vấn đề cụ thể diễn ra trong đời sống ➔ Sự việc, công việc."
  },

  // ================= BÀI 16 =================
  16: {
    "天气": "Ghép từ: 天 (Bầu trời bao la) + 气 (Luồng khí quyển luân chuyển) ➔ Trạng thái nắng mưa gió bão của bầu trời ➔ Thời tiết.",
    "热": "Chiết tự: Chấp 执 (giữ đất) bên trên bốn chấm hỏa 灬 (ngọn lửa cháy rực) ➔ Nhiệt độ bốc lên hừng hực như lửa thiêu ➔ Nóng bức, nhiệt độ cao.",
    "冷": "Chiết tự: Hai chấm băng 冫 (băng giá đông cứng) + Lệnh 令 (mùa đông ban lệnh) ➔ Băng giá thấu xương buốt giá ➔ Lạnh buốt, giá rét.",
    "雨": "Chiết tự: Vòm trời bao phủ, từng giọt nước mưa lất phất rơi xuống từ mây đen ➔ Cơn mưa, nước mưa.",
    "下雨": "Ghép từ: 下 (Rơi từ trên trời xuống) + 雨 (Mưa) ➔ Từng giọt mưa rơi tí tách phủ đầy mặt đất ➔ Trời mưa, đổ mưa.",
    "雪": "Chiết tự: Mưa Vũ 雨 đông kết lại trong lòng bàn tay Kê 彐 ➔ Từng bông hoa tuyết trắng muốt rơi nhẹ nhàng ➔ Tuyết.",
    "下雪": "Ghép từ: 下 (Rơi xuống) + 雪 (Tuyết trắng) ➔ Bông tuyết trắng xóa phủ ngập mái nhà ➔ Tuyết rơi.",
    "风": "Chiết tự: Hình cơn gió cuộn lốc bên trong có cánh côn trùng bay lượn ➔ Luồng không khí chuyển động mát rượi ➔ Ngọn gió.",
    "刮风": "Ghép từ: 刮 (Gọt giũa sắc bén) + 风 (Gió) ➔ Gió thổi ào ào rít từng cơn lạnh buốt ➔ Gió thổi, nổi gió.",
    "晴天": "Ghép từ: 晴 (Nhật 日 mặt trời rực rỡ + Thanh 青 trời trong xanh) + 天 (Ngày) ➔ Ngày trời quang mây tạnh chan hòa ánh nắng ➔ Ngày nắng ráo.",
    "阴天": "Ghép từ: 阴 (Bóng râm dưới sườn đồi 阝) + 天 (Bầu trời) ➔ Mây đen che khuất mặt trời râm mát ➔ Ngày âm u, nhiều mây.",
    "太阳": "Ghép từ: 太 (To lớn vô cùng) + 阳 (Mặt trời tỏa dương khí ấm áp) ➔ Vầng thái dương nguồn sống của muôn loài ➔ Mặt trời.",
    "暖和": "Ghép từ: 暖 (Nhật 日 ánh nắng chiếu rọi ấm áp) + 和 (Dịu nhẹ êm ái) ➔ Tiết trời ấm cúng dễ chịu xua tan cái lạnh ➔ Ấm áp.",
    "凉快": "Ghép từ: 凉 (Hai chấm băng 冫 se lạnh) + 快 (Khoan khoái trong lòng) ➔ Làn gió thu làm lòng người sảng khoái ➔ Mát mẻ, khoan khoái.",
    "季节": "Ghép từ: 季 (Con bò non đón vụ mùa) + 节 (Đốt phân chia thời gian) ➔ Bốn khoảng thời gian tuần hoàn trong năm ➔ Mùa màng, mùa.",
    "春": "Chiết tự: Tam nhân 三人 đón ánh nắng mặt trời Nhật 日 khi mầm non nhú nở ➔ Mùa khởi đầu sự sống trăm hoa đua nở ➔ Mùa xuân.",
    "夏": "Chiết tự: Người đội nón lớn bước đi chậm rãi dưới ánh nắng chói chang ➔ Mùa ve kêu râm ran nóng nực ➔ Mùa hè, mùa hạ.",
    "秋": "Chiết tự: Hòa 禾 (cây lúa chín vàng) + Hỏa 火 (màu đỏ rực của lá phong) ➔ Mùa gặt hái lúa vàng lá phong rơi ➔ Mùa thu.",
    "冬": "Chiết tự: Hai chấm băng 冫 (băng tuyết kết tinh) ở cuối năm ➔ Mùa tuyết rơi giá lạnh nhất trong năm ➔ Mùa đông.",
    "伞": "Chiết tự: Hình chiếc dù xòe rộng nan hoa che chở cho bốn người bên dưới ➔ Đồ vật che mưa che nắng ➔ Cái ô, cái dù.",
    "度": "Chiết tự: Quảng 广 (mái nhà) + Hựu 又 (bàn tay vạch thước đo) ➔ Đơn vị đo góc hoặc nhiệt độ thời tiết ➔ Độ (nhiệt độ).",
    "气温": "Ghép từ: 气 (Khí quyển) + 温 (Nước 氵 ấm áp mặt trời rọi) ➔ Mức độ nóng lạnh của bầu không khí ➔ Nhiệt độ không khí.",
    "非常": "Chiết tự: Phi 非 (không phải) + Thường 常 (bình thường tẻ nhạt) ➔ Vượt xa mức độ thông thường gấp bội ➔ Cực kỳ, vô cùng.",
    "有点儿": "Ghép từ: 有点 (Có một chút xíu) + 儿 ➔ Biểu thị mức độ nhẹ nhưng thường mang sắc thái hơi phiền toái ➔ Hơi hơi, hơi có phần.",
    "最": "Chiết tự: Nhật 日 (mặt trời tột đỉnh) + Lấy 取 (chiếm đoạt vị trí quán quân) ➔ Đạt đến cực hạn không ai sánh bằng ➔ Nhất, đứng đầu."
  }
};
